### ISSUE TITLE
Extract SmtpMailClient to plugin

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#115]
System.Net.Mail is not supported in .net core cross platform, so we should extract it into a plug in package. We should also look into [MailKit](https://github.com/jstedfast/MailKit) which may be a better choice for a cross platform mail plugin.

We should create a default IMailClient implementation that either logs the output or writes the mail content to a mail drop directory.

**Comment by gregbty** [comment]
Just wanted to note that System.Net.Mail will be supported in .NET Standard 2.0.

https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

**Comment by HeyJoel** [comment]
Thanks. For some reason I was under the impression that System.Net.Mail wouldn't be getting a full cross platform implementation in .net core 2 but that doesn't appear to be the case, which is good news. That should mean we can re-implement a default smtp client in the core package when .net core 2 drops.

I was actually going to make a start on this in the next few days and would ideally like to have something running on .net standard 1.6 so I'll see how much effort it is to get a MailKit plugin up and running and work from there.

**Comment by HeyJoel** [comment]
We now have a couple of options here:

- [Cofoundry.Plugins.Mail.MailKit](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.MailKit)
- [Cofoundry.Plugins.Mail.SendGrid](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.SendGrid)

A native System.Net.Mail version may be included in the core package when .Net Standard 2 drops.
