### ISSUE TITLE
Html editor tool bar options not working

### ISSUE THREAD

**Issue by ricalebro** [cofoundry-cms/cofoundry#129]
Whatever options I give the html editor in a page module it only displays the basic formatting toolbar.

I'm trying to add
`        [Required]
        [Display(Name = "Text", Description = "Rich text displayed at full width")]
        [Html(HtmlToolbarPreset.AdvancedFormatting, HtmlToolbarPreset.Headings, HtmlToolbarPreset.Media, HtmlToolbarPreset.Source)]
        public string HtmlText { get; set; }`

**Comment by HeyJoel** [comment]
Fixed in https://github.com/cofoundry-cms/cofoundry/commit/86db584650fceddd18b832bc92801c4c6fbd5ba0, will go into 0.1.10 release.
