### ISSUE TITLE
User list doesn't display username, only First/Last names

### ISSUE THREAD

**Issue by ricalebro** [cofoundry-cms/cofoundry#131]
This is an issue in my case as my users don't have first/last names, so there's no way of identifying users in the list.

**Comment by HeyJoel** [comment]
In addition, we should make the first/last names not required as there are many situations where a username is all that is required.

**Comment by HeyJoel** [comment]
This fix will be released with the 0.20 release. The server side requirement for the first/last name props will be address in #80
