### ISSUE TITLE
"web.config" should read "appsettings.json" in wiki documentation

### ISSUE THREAD

**Issue by englishmatt** [cofoundry-cms/cofoundry#151]
The [wiki page](https://github.com/cofoundry-cms/cofoundry/wiki/Installing#configuring-the-site) outlining installation of Cofoundry should refer to `appsettings.json` and not `web.config`, as is standard with .NET Core.

It should  be:

> 1. Create and open your `appsettings.json` and add a connection string named 'Cofoundry' that points to the database you just created

Not

>1. Open your `Web.config` and add a connection string named 'Cofoundry' that points to the database you just created

**Comment by HeyJoel** [comment]
Fixed, thank you!
