### ISSUE TITLE
Relative times in admin UI confusing

### ISSUE THREAD

**Issue by englishmatt** [cofoundry-cms/cofoundry#152]
The string used to indicate relative times is "backwards". It should be:

> 4 hours ago

Not

> 4 hours from now

This means it's going to happen in the future. See screenshot below.

![image](https://user-images.githubusercontent.com/1330991/36919894-242280f6-1e1c-11e8-85d8-b616bb2fd398.png)

**Comment by HeyJoel** [comment]
[Fixed](https://github.com/cofoundry-cms/cofoundry/commit/48f139a8c3cc898f6eb7c0ad001abce638ee3d02). UTC DateTimes weren't being formatted correctly in the api so they were being interpreted as local times.
