### ISSUE TITLE
'Manage in Visual Editor' button disappears on hover

### ISSUE THREAD

**Issue by englishmatt** [cofoundry-cms/cofoundry#153]
### Issue Description
When moving the mouse cursor near the *Manage in Visual Editor* button in the administrative UI, the button disappears. Once it has disappeared it is not possible to click it, making it impossible to manage content in the visual editor in Firefox.

![image](https://i.gyazo.com/0d1101b7cf35780a0b982646a9b4a1de.gif)

### Expected Behavior
The *Manage in Visual Editor* button should not disappear, so that I can click on it.

Browser: Firefox 58.0.2
OS: Windows 10

**Comment by HeyJoel** [comment]
Fixed, but will go into the 0.2.1 release which is a little way off. A work around is to use the *Browse To Page* button under the main *Edit* button, or you can use the [pre-release packages](https://myget.org/gallery/cofoundry) to get the fix.

**Comment by englishmatt** [comment]
Sweet! Thanks for getting to these so quickly.
