### ISSUE TITLE
Update to .NET 2.1

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#154]
- [x] Update to .NET 2.1
- [X]  Look into [SourceLink](https://github.com/dotnet/sourcelink) support
- [X]  Be mindful of this [cookie consent](https://jdono.com/2018/05/31/asp-net-core-2-1-0-individual-authentication-issues-after-migrating-from-2-0-x/) gotcha.

Not implemented:

-  **Replace `DbDateTimeMapper` with EF 2.1 native type mapping:** Given some of the [limitations with query translation](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#limitations) on this feature, I don't think it's worth changing and dealing with potential query translation issues. Let's defer until there is a clear need for it.
- **Handle view compilation changes:** Documentation is thin on the ground for the specifics of this feature and will take some time to dig in to and experiment with. We can look at this as a separate job in line with #137

**Comment by runxc1** [comment]
Hey hey it's now out there in the wild

**Comment by HeyJoel** [comment]
Added, will be released in v0.4
