### ISSUE TITLE
ArgumentNullException: Value cannot be null. Parameter name: codeDefinition

### ISSUE THREAD

**Issue by wzowee** [cofoundry-cms/cofoundry#165]
Hi I've followed the setup instructions as per

https://github.com/cofoundry-cms/cofoundry/wiki/Installing

and then here for a Custom Entity

https://github.com/cofoundry-cms/cofoundry/wiki/Custom-Entities

I can create an instance of the Custom Entity however then when trying to retrieve the list of Entities via the Admin Interface I'm receiving a 500 Server error code on the route 
/Admin/Api/custom-entity-definitions/CEPRT/custom-entities?pageNumber=1&pageSize=20

Where CEPRT is the DefinitionCode for my Customer Entity.

A partial stack trace for the error is:

System.ArgumentNullException: Value cannot be null.
Parameter name: codeDefinition
   at Cofoundry.Domain.CustomEntityDefinitionSummaryMapper.Map(ICustomEntityDefinition codeDefinition)
   at Cofoundry.Domain.GetCustomEntityDefinitionSummaryByCodeQueryHandler.ExecuteAsync(GetCustomEntityDefinitionSummaryByCodeQuery query, IExecutionContext executionContext)
   at Cofoundry.Domain.CQS.QueryExecutor.<ExecuteQueryAsync>d__8`2.MoveNext()

I'm using the Super User account when working in the Admin section.

Here are my test CustomEntity Classes. 

```
using Cofoundry.Domain;

namespace CMS.Example.Models
{
    public class PortraitDataModel : ICustomEntityDataModel
    {
        [Html]
        public string Body { get; set; }
    }

    public class PortraitCustomEntityDefinition : ICustomEntityDefinition<PortraitDataModel>
    {
        /// <summary>
        /// This constant is a convention that allows us to reference this definition code 
        /// in other parts of the application (e.g. querying)
        /// </summary>
        public const string DefinitionCode = "CEPRT";

        /// <summary>
        /// Unique 6 letter code representing the module (the convention is to use uppercase)
        /// </summary>
        public string CustomEntityDefinitionCode => DefinitionCode;


        /// <summary>
        /// Singlar name of the entity
        /// </summary>
        public string Name => "Portrait";

        /// <summary>
        /// Plural name of the entity
        /// </summary>
        public string NamePlural => "Portraits";

        /// <summary>
        /// A short description that shows up as a tooltip for the admin 
        /// panel.
        /// </summary>
        public string Description
        {
            get { return "A portrait page"; }
        }

        /// <summary>
        /// Indicates whether the UrlSlug property should be treated
        /// as a unique property and be validated as such.
        /// </summary>
        public bool ForceUrlSlugUniqueness
        {
            get { return true; }
        }

        /// <summary>
        /// Indicates whether the url slug should be autogenerated. If this
        /// is selected then the user will not be shown the UrlSlug property
        /// and it will be auto-generated based on the title.
        /// </summary>
        public bool AutoGenerateUrlSlug
        {
            get { return true; }
        }

        /// <summary>
        /// Indicates whether this custom entity should always be published when 
        /// saved, provided the user has permissions to do so. Useful if this isn't
        /// the sort of entity that needs a draft state workflow
        /// </summary>
        public bool AutoPublish
        {
            get { return true; }
        }

        /// <summary>
        /// Indicates whether the entities are partitioned by locale
        /// </summary>
        public bool HasLocale
        {
            get { return false; }
        }
    }
}
```

**Comment by HeyJoel** [comment]
Hi there, the custom entity definition code should be 6 characters long which is perhaps what is causing the issue. Can you change it and see if that works?

In any case, this is something we should validate for and there isn't a good reason why we couldn't pad the extra space internally.

**Comment by wzowee** [comment]
That was it - changed the code to be 6 chars long and it's now working. Thanks.
