### ISSUE TITLE
Do Rest Api and Token OAuth suppored out of the box?

### ISSUE THREAD

**Issue by biapar** [cofoundry-cms/cofoundry#199]
Do Rest Api and Token OAuth ( remote login ) suppored out of the box?

**Comment by HeyJoel** [comment]
Not out of the box, you need to wire up you SSO manually, see #162 and #163. Do those issues cover your needs or is there a different scenario you'd like us to support?

**Comment by biapar** [comment]
My scenario is: built custom API protected by OAUTH2. That apis used by mobile or SPA application.

**Comment by HeyJoel** [comment]
Ok, unfortunately that's not something that's available out of the box, but it is something we should be able to provide. I've added your scenario to #163, and also added #200 which should make this kind of thing possible without having to dig into the framework.

I'm going to close this as it's covered by those other issues, but feel free to open it up again if you have unresolved questions.

**Comment by biapar** [comment]
Check here if you want some info ( I'm using it and customize ). I think that maybe we can port some parts of code to integrate an OAuth server.
https://github.com/mattbrailsford/umbraco-authu
