### ISSUE TITLE
Deployment Results in error: Permission Validation Check Failed. Permission Type: Cofoundry.Domain.CustomEntityReadPermission

### ISSUE THREAD

**Issue by runxc1** [cofoundry-cms/cofoundry#205]
So I have been pretty happily playing with Cofoundry and recently tried deploying the app and coping the development server up to the live site and keep running into the error below when browsing the homepage and don't see any reason this would get flagged.  Are there some .lock files or something that stops you from moving to a different site?

`Permission Validation Check Failed. Permission Type: Cofoundry.Domain.CustomEntityReadPermission. UserId: 

   at Cofoundry.Domain.PermissionValidationService.EnforcePermission(IPermissionApplication permission, IUserContext userContext)
   at Cofoundry.Domain.PermissionValidationService.EnforcePermission(IEnumerable`1 permissions, IUserContext userContext)
   at Cofoundry.Domain.ExecutePermissionValidationService.Validate[TQuery,TResult](TQuery query, IAsyncQueryHandler`2 queryHandler, IExecutionContext executionContext)
   at Cofoundry.Domain.CQS.QueryExecutor.<ExecuteQueryAsync>d__8`2.MoveNext()`

**Comment by HeyJoel** [comment]
Likely that the anonymous user does not have permission to your custom entity. When logged in you would not see this error. In the admin UI go to roles and give the anonymous user read permissions to your entity.

You can add this programatically but I'm on the ole mobile now and don't have the link to hand.

**Comment by HeyJoel** [comment]
Here's [the link to the docs for code based permission initializers](https://github.com/cofoundry-cms/cofoundry/wiki/Roles-&-Permissions#managing-roles-in-code). I wonder if we could do better here as it's not immediately obvious that the permission isn't added by default.

**Comment by runxc1** [comment]
So I finally had a chance to look at this and it was in fact due to the fact that by default a page can't query for data if the user is anonymous.   The Rights management system is quite robust but seems a little overhanded for a CMS that is primarily about viewing Content.   I read the documentation on creating Permissions and Roles but there isn't a way to give the read access by default to a custom entity for anonymous.  I started playing with the Blog Sample so that must have been data that was auto scripted in.   

I would have thought the default would be to allow read access.  With that said maybe you could define the default Read access in the ICustomEntityDefinition?

**Comment by HeyJoel** [comment]
I think this is a problem we can solve. While it kinda makes sense if you know the system it's not very intuitive and has tripped me up before. Having to set the permissions manually in the admin UI after delpoy is not an ideal solution, and programatically adding the permission is a lot of effort if you're only using basic roles and permissions.

I've added a issue #206 to cover it with some ideas on what we can do.

I'll close this for now, but let me know if #206 doesn't cover your scenario.

**Comment by HeyJoel** [comment]
FYI #206 is fixed in the upcoming 0.4 release. The role initializers will run for any new entities/permissions added to the system so for this issue, the anonymous role will now be initialized with read permission for the newly created custom entity type and would not throw the permission error.
