### ISSUE TITLE
Version 0.3.2 mistmatch

### ISSUE THREAD

**Issue by cesarcastrocuba** [cofoundry-cms/cofoundry#233]
Hello, I'm currently using the 0.3.2 version located in nuget  but I realized that your current Master branch and https://github.com/cofoundry-cms/cofoundry or https://github.com/cofoundry-cms/cofoundry/releases/tag/v0.3.2 don't have the same version of the libraries, I think you uploaded a previous version 0.2.0 or another one in the source code,

Could you please update the current master branch and the release with correct files?

**Nuget**

![nuget](https://user-images.githubusercontent.com/13800488/44617992-06473900-a86e-11e8-9078-241b57f44c1e.JPG)

**SourceCode**

![sourcecode](https://user-images.githubusercontent.com/13800488/44617995-0b0bed00-a86e-11e8-91aa-5c9f1f9cbbe6.JPG)

**Comment by HeyJoel** [comment]
Closing this as I don't think there's any action to take here.
