### ISSUE TITLE
Localized site 404 error

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#240]
I have a problem when try to create a new page using market field. If I create localized pages (e.g. /en/home and /es/home) it has made successful and appears in page list, however when try to browse these pages only works fine the Spanish page. English page gets 404 not found error.
I changed "isActive" locales indicator in database, and I also added the next code to startup.cs class in Configure method:

```
var supportedCultures = new[]     {
                  new CultureInfo("en"),
                  new CultureInfo("es")
              };

 var options = new RequestLocalizationOptions()
              {
                  DefaultRequestCulture = new RequestCulture("en"),
                  SupportedCultures = supportedCultures,
                  SupportedUICultures = supportedCultures
              };
 app.UseRequestLocalization(options).UseCofoundry();
```
There is anything that I should add?

![1](https://user-images.githubusercontent.com/8802992/45081944-9603a780-b0f8-11e8-929b-2b865a282798.PNG)
![2](https://user-images.githubusercontent.com/8802992/45081945-9603a780-b0f8-11e8-8c12-c541a5aca101.PNG)
![3](https://user-images.githubusercontent.com/8802992/45081946-9603a780-b0f8-11e8-95b3-49e1ea64e94f.PNG)

**Comment by HeyJoel** [comment]
Localization is not well supported yet in Cofoundry, the feature is tracked in #43. The documentation in the wiki refers to a pre-netcore version of Cofoundry where localization was different, so I'll get that updated.

For your issue specifically, you're missing a `RequestCultureProvider` to set the thread culture based on the url path. It's likely that when we work on #43 we'll do all this for you, or provide several strategies for capturing the culture of the request. For now, here's some amended startup code which includes a simple custom culture provider:

```csharp
public void Configure(IApplicationBuilder app)
{
    var defaultCulture = new RequestCulture("en");
    var supportedCultures = new[]
    {
            defaultCulture.Culture,
            new CultureInfo("es")
    };

    var options = new RequestLocalizationOptions()
    {
        DefaultRequestCulture = defaultCulture,
        SupportedCultures = supportedCultures,
        SupportedUICultures = supportedCultures,
    };

    options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(context =>
    {
        foreach (var supportedCulture in supportedCultures)
        {
            var segementToTest = '/' + supportedCulture.IetfLanguageTag;
            if (context.Request.Path.StartsWithSegments(segementToTest, StringComparison.OrdinalIgnoreCase))
            {
                var result = new ProviderCultureResult(supportedCulture.IetfLanguageTag);
                return Task.FromResult(result);
            }
        }

        return Task.FromResult(new ProviderCultureResult(defaultCulture.Culture.IetfLanguageTag));
    }));

    app
        .UseRequestLocalization(options)
        .UseCofoundry();
}
```

**Comment by ernestoSerra** [comment]
The problem was solved, thanks.
