### ISSUE TITLE
Redirection (301/302) management

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#245]
Hello,
It would be nice if we can manage redirections 301 and perhaps 302.
For example when we delete a page, the GUI could propose a deletion with a redirection to a new page (better for SEO).
A "redirection" module would complete the mechanism.
Thanks

**Comment by HeyJoel** [comment]
Duplicate of #143 and #41, although I've added notes about the term *redirect* and the possible need for 302 redirects (although I can't think of a specific example yet).

If you have any more feedback please add it to those issues, thanks!

**Comment by dumboster** [comment]
Ok, thanx !
