### ISSUE TITLE
Tags added to Documents are not saved correctly

### ISSUE THREAD

**Issue by mjsmart** [cofoundry-cms/cofoundry#247]
If you add multiple tags to a Document e.g. 'tag1, tag2', when you click save a single tag of 'Tag1tag2' will be displayed instead.

This is present in Cofoundry 0.4.1 and 0.3.6.

**Comment by mjsmart** [comment]
Tags are also not saving for Images at all.

**Comment by HeyJoel** [comment]
Tags saving and loading fixed for both image and document assets. This will be released in v0.5
