### ISSUE TITLE
DefaultHtmlSanitizationRuleSetFactory incorrectly whitelists class attribute

### ISSUE THREAD

**Issue by mjsmart** [cofoundry-cms/cofoundry#249]
The class attribute is incorrectly whitelisted as a CSS property rather than an attribute causing it to be stripped out.

**Comment by HeyJoel** [comment]
Thanks. You're probably already aware, but you can [customize the ruleset](https://github.com/cofoundry-cms/cofoundry/wiki/Html-Sanitizer#customizing-the-sanitization-ruleset) to get around the bug.

**Comment by mjsmart** [comment]
Yes, I was customizing the ruleset to allow the video tag to be used when I noticed the error.

**Comment by HeyJoel** [comment]
Fixed, will be released in v0.5
