### ISSUE TITLE
GetCustomEntitySummariesByIdRangeQuery - Setting missing in constructor

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#252]
Hello,

It seems there is a bug in GetCustomEntitySummariesByIdRangeQuery class due to a modification done on 2018-08-02 :
`        public GetCustomEntitySummariesByIdRangeQuery(`
`            IReadOnlyCollection<int> customEntityIds`
`            )`
`        {`
`            if (customEntityIds == null) throw new ArgumentNullException(nameof(customEntityIds));`
`        }`
=>            `CustomEntityIds = customEntityIds;` is missing

**Comment by HeyJoel** [comment]
Fixed, will be released in v0.5
