### ISSUE TITLE
Customization of 404 and 500 pages

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#254]
Hello,
Is it possible to customize the title of the error pages ?
If not, is it scheduled ?
Thank you

**Comment by HeyJoel** [comment]
Do you mean the content of the error page or the Title meta data property passed to the layout?

- To create custom error pages check out [the docs](https://github.com/cofoundry-cms/cofoundry/wiki/Custom-Error-Pages)
- If you already have a custom error page and want to change the document title you can either handle this in your layout e.g. using `ViewBag` the traditional MVC way, or you should be able to update the view model `PageTitle` property from the view if you're using that in your layout.
- Lastly, if you don't have a custom error page but just want to change the PageTitle of the view model you can override the `IPageViewModelBuilder` implementation and do something completely custom with the model, see the [custom view model type docs](https://github.com/cofoundry-cms/cofoundry/wiki/Custom-View-Model-Types#overriding-ipageviewmodelbuilder) for more info.

**Comment by dumboster** [comment]
When I started my project, I got the source code from Cofoundry.Samples.SimpleSite (_Layout.cshtml, Error.cshtml and NotFound.cshtml) and now I wanted to know what you recommended.
Thanks for you answer, it would have to be ok with it.
