### ISSUE TITLE
Display VideoList from API

### ISSUE THREAD

**Issue by Shilpakopparad** [cofoundry-cms/cofoundry#258]
Hi,
     I have to Implement the Functionality where there will be 2 users Admin, and Normal user.
Admin after login will be able to see the video list fetched from the API, able to edit and publish the videos.
Normal users will able to see the published videos after login.
I need help to implement this functionality. Please, can u help me to do this?

**Comment by HeyJoel** [comment]
Hi, I don't really understand what in particular you need. What is the API, an external one e.g. Vimeo? Do you want to display these in a page using a page block type?

**Comment by HeyJoel** [comment]
Closing, feel free to re-open if you want to add more info.
