### ISSUE TITLE
Paging in pages selector

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/cofoundry#279]
Hello,

I am using [PageAttribute] in order to link an element to a page (for a menu), but the selector in UI presents only the 20 first pages because of API paging : /admin/api/pages?**pageSize=20**&text=
Is it normal?

Thanks

**Comment by HeyJoel** [comment]
The selector UI is filtered list, so although it only displays one page you can filter the list by typing in the input box.

As a future development we could:

- Add a placeholder e.g. *filter...*
- Increase the page size
- Implement paging (non-trivial)

**Comment by dumboster** [comment]
It was so simple ^^ Sorry for this stupid question!

**Comment by HeyJoel** [comment]
It's come up before so I think there's an issue for us to solve here, although not urgently. I've added #280 to cover this.
