### ISSUE TITLE
Cannot publish Custom Entity

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#283]
Hi, 
I tried to creat a custom entity in backend, but it is not published correctly. 
I used AddCustomEntityCommand and I set Publish = true. In database, the custom entity is created in table CustomEntity and it has PublishStatusCode = "P". In table CustomEntityVersion it has a WorkFlowStatus = 4. 
Apparently it works fine, but when I try to get custom entity by command GetCustomEntityRenderSummariesByDefinitionCodeQuery whit PublishStatusQuery.Published it doesn't appear. 

Can you help me please?

**Comment by ernestoSerra** [comment]
Hi, 
the problem was that I also changed publisDate to DateTime.Now. If I remove this, it works fine. 

Thanks

**Comment by HeyJoel** [comment]
You should avoid setting these properties directly in the database and use the Cofoundry commands instead e.g. `PublishCustomEntityCommand`. This will ensure the properties are set correctly, lookup tables are updated and caches are invalidated.

Also note that all dates should be utc i.e. `DateTime.UtcNow`
