### ISSUE TITLE
GOOGLE ANALYTICS UA ID is not saving in the database

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#285]
Hi,
I see that there is a field "GOOGLE ANALYTICS UA ID" in site settings but when I write and save any string in this field, it put automatically to none. If I see the database, I can check that the field is empty.

¿Is "GOOGLE ANALYTICS UA ID" field implemented or it exist without any functionality?

![image](https://user-images.githubusercontent.com/8802992/49360099-7b7da200-f6d8-11e8-8ab4-deea7c43419c.png)

Thanks

**Comment by HeyJoel** [comment]
I'm surprised to see that setting in there, I thought I had removed it. I probably forgot to remove it from the UI.

There's no built in GA functionality so please ignore this setting. #243 covers custom site settings and I'll get this removed from the UI in the next update.

**Comment by HeyJoel** [comment]
GA ID field has been removed in v0.6
