### ISSUE TITLE
Permanent redirects

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#286]
Hi 
Are there any form to make permanent redirects with cofoundry?
Thanks!

**Comment by HeyJoel** [comment]
We have a partially implemented system for user defined rewrite rules, #143 covers finishing off that feature. I would avoid using it until we have finished implementing it. Instead you could use your webserver redirect configuration (e.g. IIS) or try the [ASP.NET rewrite middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1)
