### ISSUE TITLE
Using an ORM different than Entity Framework

### ISSUE THREAD

**Issue by jromerus** [cofoundry-cms/cofoundry#287]
Hi!

You say in several wiki pages like https://github.com/cofoundry-cms/cofoundry/wiki/Data-Access that it is possible using another ORM, but, do you have a doc or sample explaining how to face that task?

**Comment by HeyJoel** [comment]
What we mean by that is that you can use a different ORM for your own data access in your site, you don't need to use the same ORM as Cofoundry. What we're not saying here is that there's ready to use drop in alternative.

E.g. if u prefer to use Dapper to access your custom data tables then go ahead and use it, but there's no special drop in package.

Perhaps the docs are misleading and it's better to not mention that?

**Comment by HeyJoel** [comment]
I've updated the docs based on your feedback, thanks =)
