### ISSUE TITLE
Unhandled exception with new project from template

### ISSUE THREAD

**Issue by wireless-r** [cofoundry-cms/cofoundry#290]
I'm getting an unhandled exception. I have just created a new project with `dotnet new cofoundry-web -n ExampleApp`. Then created database and updated connection string. Then press debug, it opens browser and directly throws exception.

![screenshot](https://user-images.githubusercontent.com/28116634/50286476-c7ae3d80-045f-11e9-857e-68ae1731c427.png)

**Comment by HeyJoel** [comment]
Hi, first of all can I check what version of SQLServer you're running? Only 2012 or later is supported.

**Comment by wireless-r** [comment]
I'm using LocalDB which was included with Visual Studio 2017.

**Comment by HeyJoel** [comment]
I'm not too familiar with LocalDb, but after a bit of research I found a connection string that works for me:

```json
{
  "Cofoundry": {
    "Database:ConnectionString": "Server=(localdb)\\mssqllocaldb;Database=ExampleApp;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
}
```

In json config make sure you escape the backslash character. I suspect Cofoundry can't connect to the db so make sure the connection string is valid.

If you continue to have issues, check the debug log. The auto-update process runs in a hosted service so the exception will be logged from there.

**Comment by wireless-r** [comment]
It works with this connection string.

**Comment by HeyJoel** [comment]
FYI I think we should be able to show you the error details in the response if you have the developer exception page enabled, that would be much more intuative. I've added issue #291 to cover this.
