### ISSUE TITLE
Cofoundry 0.6.0 --  Updating custom page entity block errors with Method Not Allowed

### ISSUE THREAD

**Issue by jhaygood86** [cofoundry-cms/cofoundry#294]
1. Open an existing custom entity in the visual editor
2. Attempt to edit the content
3. Attempt to save the content
4. Notice Method Not Allowed error

**Comment by HeyJoel** [comment]
@jhaygood86 Did you get this working? I wasn't able to reproduce it.

**Comment by HeyJoel** [comment]
Closing, not reproducable
