### ISSUE TITLE
Template.Region closes <p>

### ISSUE THREAD

**Issue by Enlatic** [cofoundry-cms/cofoundry#297]
Hi,

New to Cofoundry… I am trying to migrate a static website to cofoundry. Ran into some minor issues.
I could probably rewrite the css to work around it... But i rather not :)

My code.

> < p class="blockquote blockquote-primary">
>                           @(await Cofoundry.Template.Region("QuoteDescription")
>                                  .AllowBlockType<RichTextDataModel>()
>                                  .EmptyContentMinHeight(150)
>                                  .InvokeAsync())
>                       < /p>

Rendered code.
>< p class="blockquote blockquote-primary">< /p>
 >< p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 >< br>
 >Pellentesque eu leo nec metus lacinia tristique.
 >< /p>
 >< p>< /p>

Somehow the region insertion screws up the structure.

Is this intended? Alternatively how do I add my custom class attributes to the generated p>?

Sorry for the crappy code example.. dont know why... but I cant add html code to show.. so I a space in the HTML tag everywhere...

**Comment by HeyJoel** [comment]
Well, the HTML spec doesn't allow nested `<p>` tags, so I expect the HTML parser is correcting that automatically (the browser might do the same). If you change your container tag to a valid container element like a `<div>` then you should find it works.

**Comment by Enlatic** [comment]
fair enough.. I'll change my code/css.

**Comment by HeyJoel** [comment]
Having said that I just realised that the region code shouldn't touch the container code, so it is more likely that the html it is being output in the response as you expect, but the browser is automatically correcting the html to make it conform to HTML5 which makes it render unexpectedly.

**Comment by HeyJoel** [comment]
Closing, do let me know if this isn't resolved.
