### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#299]
There is a broken link on 

> https://www.cofoundry.org/docs/content-management/custom-entities

on line:

> 4. Add UI MetaData attributes, see a list of options here.

Link should go to data anotations page, 

> https://www.cofoundry.org/docs/framework/data-model-annotations

but it returns page not found.

**Comment by HeyJoel** [comment]
Thanks for letting us know, that's now fixed :)
