### ISSUE TITLE
SqlNullValueException: 'Data is Null' when update to Cofoundry 0.6 from 0.5

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#300]
Hi, 
I update Cofoundry to version 0.6 and .net core to 2.2 and I get an SQL error when execute. 
```
SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
System.Data.SqlClient.SqlBuffer.get_String()
```
I think that it is produced because a custom dbContext that use to load a custom table can't map data to model. I use the specified way by Cofoundry to create a dbContext , and in Cofoundry 0.5 it works fine, but not after update. 

```
public class MySiteDbContext : DbContext
{
    private readonly ICofoundryDbContextInitializer _cofoundryDbContextInitializer;

    public MySiteDbContext(ICofoundryDbContextInitializer cofoundryDbContextInitializer)
    {
        _cofoundryDbContextInitializer = cofoundryDbContextInitializer;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        _cofoundryDbContextInitializer.Configure(this, optionsBuilder);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAppSchema()
            .ApplyConfiguration(new MyClassMap());
    }

    public DbSet<MyClass> data{ get; set; }
}
```

Can you help me please? 

Thanks

**Comment by ernestoSerra** [comment]
Hi, 
I have checked if it was a .net core or EF error but I have not found any information about it.
The error occurs when I get a Locale object from dbcontext as follows:

`var locale = _dbContext.Locales.Where(.....).FirstOrDefault();
`

If you see the code that I posted in previous post:

- Locales is data
- Locale is MyClass 
- LocaleMap is MyClassMap
```
...:DBContext {
.....
modelBuilder .HasAppSchema() .ApplyConfiguration(new MyClassMap());
.....
 public DbSet<MyClass> data{ get; set; }
........
}
```
I also share screenshots that can help you. It seems that dbContext is created succesfully, but can't map "Locales". 

![image](https://user-images.githubusercontent.com/8802992/52283965-ced3d100-2963-11e9-9f7d-809186540db4.png)

![image](https://user-images.githubusercontent.com/8802992/52285965-9e8e3180-2967-11e9-952e-f81c2c0b61e4.png)


Thanks!

**Comment by HeyJoel** [comment]
This still looks very much like an EF problem. Possibly either a problem with your map definition or in your query where clause where you're trying to act on a property that is null.

If you create the dbContext without the Cofoundry helpers I expect you'll have the same issue.

**Comment by ernestoSerra** [comment]
Hi Joel, 
I found the error It was a EF probleme. In map class, IsRequiered() method was used in a database column that allows null values. 
I can't know why it is works in previous framework version. 

If I remove this call it works fine. 

```
 builder.Property(s => s.DefaultPage)
                //.IsRequired()  -> Remove this line 
                .HasMaxLength(50);
```


Thanks for help!
