### ISSUE TITLE
Add guide for setting up email via plugins

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#301]
A plugin is required to support email, and this is required for setting up user accounts. It's worth documenting this specifically as it might not be obvious to new users using the "dotnet new" template.

**Comment by markchilton** [comment]
Could this include instructions on setting up the forgotten password email please guys?

**Comment by HeyJoel** [comment]
@markchilton if you're referring to setting up the Cofoundry admin panel forgotten password functionality, then you just need to install and configure one of the [email plugins](https://www.cofoundry.org/docs/plugins/available-plugins).

For custom user areas we are adding the ability to customize the email templates (#215) and putting together samples and docs that cover how to setup login/forgot password flows (190). This will all be in the next v0.7 release which is still a little way off.

Is there something you're specifically trying to set up at the moment I could help with?

**Comment by markchilton** [comment]
@HeyJoel Yes I was referring to setting up the admin panel forgotten password functionality. After reading about the email plugins I understood that they were for the front end of the managed site rather than the admin section. This was after checking the various site examples and not finding any admin config examples. (Probably I have missed something).

I am trying to set up the forgotten password functionality using AWS SES. Any advice you could supply on this would be greatly appreciated.

**Comment by HeyJoel** [comment]
Because there's no standard way to send an email in .NET Core we don't include a default implementation in the base package, so it's a decision you have to make as to how you'd like to send email. The two official plugins we have are for [MailKit](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.MailKit) (sending via an SMTP server of your choice) or [SendGrid](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.SendGrid) (via the SendGrid hosted service). There is also a community plugin for [AmazonSES](https://github.com/claytondus/Cofoundry.Plugins.Mail.AmazonSes), which looks to be what you're after.

The plugins are for any email sent using our [mail framework](https://www.cofoundry.org/docs/framework/mail) which includes emails sent by the Cofoundry admin panel.

**Comment by markchilton** [comment]
@HeyJoel Perfect. Thanks very much for your help

**Comment by HeyJoel** [comment]
I've added an additional "essential plugins" section to the [installation docs](https://www.cofoundry.org/docs/getting-started/installing), so hopefully this points people in the right direction.
