### ISSUE TITLE
PlatformNonSupportedException when publish page

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#303]
Hi, 
I get an error "PlatformNotSupportedException" when try to publish a page. 
Do you know what it can be?

> PlatformNotSupportedException: This platform does not support distributed transactions.
> System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(byte[] propagationToken)
> System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(byte[] propagationToken)
> System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
> System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)
> System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
> System.Transactions.Transaction.Promote()
> System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)
> System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, byte[] whereabouts)
> System.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, byte[] whereAbouts)
> System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
> System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
> System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
> System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
> System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, uint waitForMultipleObjectsTimeout, bool allowCreate, bool onlyOneCheckConnection, DbConnectionOptions userOptions, out DbConnectionInternal connection)
> System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
> Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(bool errorsExpected, CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, bool errorsExpected)
> Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable<T>+AsyncEnumerator.BufferlessMoveNext(DbContext _, bool buffer, CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable<T>+AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
> System.Linq.AsyncEnumerable+SelectEnumerableAsyncIterator<TSource, TResult>.MoveNextCore(CancellationToken cancellationToken) in Select.cs
> System.Linq.AsyncEnumerable+AsyncIterator<TSource>.MoveNext(CancellationToken cancellationToken) in AsyncIterator.cs
> System.Linq.AsyncEnumerable.FirstOrDefault_<TSource>(IAsyncEnumerable<TSource> source, CancellationToken cancellationToken) in First.cs
> Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+TaskResultAsyncEnumerable<T>+Enumerator.MoveNext(CancellationToken cancellationToken)
> System.Linq.AsyncEnumerable+SelectEnumerableAsyncIterator<TSource, TResult>.MoveNextCore(CancellationToken cancellationToken) in Select.cs
> System.Linq.AsyncEnumerable+AsyncIterator<TSource>.MoveNext(CancellationToken cancellationToken) in AsyncIterator.cs
> Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider+ExceptionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery<TResult>(QueryContext queryContext, Func<QueryContext, IAsyncEnumerable<TResult>> compiledQuery, IDiagnosticsLogger<Query> logger, Type contextType)
> Cofoundry.Domain.PublishPageCommandHandler.ExecuteAsync(PublishPageCommand command, IExecutionContext executionContext) in PublishPageCommandHandler.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.UpdatePageDraftVersionCommandHandler.ExecuteAsync(UpdatePageDraftVersionCommand command, IExecutionContext executionContext) in UpdatePageDraftVersionCommandHandler.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in CommandExecutor.cs
> Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command) in CommandExecutor.cs
> Cofoundry.Web.ApiResponseHelper.RunCommandAsync<TCommand>(Controller controller, TCommand command) in ApiResponseHelper.cs
> Cofoundry.Web.Admin.PageVersionsApiController.PatchDraft(int pageId, IDelta<UpdatePageDraftVersionCommand> delta) in PageVersionsApiController.cs
> Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
> System.Threading.Tasks.ValueTask<TResult>.get_Result()
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
> Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
> Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in AutoUpdateMiddleware.cs
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
> Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
> Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by HeyJoel** [comment]
That error indicates that .NET is trying to enlist the db statements in a distributed transaction. Typically that would be if you're doing work in two different databases in the same transaction scope or using two different connection strings for the same database. 

That shouldn't happen ordinarily in Cofoundry code but perhaps you're doing something in a message handler that is causing the problem. Presumably this wasn't an issue before, what changed?

I can't see what that would be looking at the exception and I'm away on holiday at the moment, but hopefully that might point you in the right direction.

**Comment by ernestoSerra** [comment]
Hi, 
Thanks for the answer. 
The problem was that we try to use multiple instance of CofoundryDbContext.
