### ISSUE TITLE
The first time the installation was run, the database could create a data table, but a database error occurred in AutoUpdate.

### ISSUE THREAD

**Issue by GetCodeHub** [cofoundry-cms/cofoundry#306]
An unhandled exception occurred while processing the request.
SqlException: 'throw' 附近有语法错误。
'throw' 附近有语法错误。
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

AutoUpdateFailedException: Error updating the system: 'throw' 附近有语法错误。
'throw' 附近有语法错误。
Cofoundry.Web.AutoUpdateMiddleware.WaitForCompletionAsync(HttpContext cx, AutoUpdateState autoUpdateState) in AutoUpdateMiddleware.cs, line 102

**Comment by HeyJoel** [comment]
Hi, only SQL server 2012 or later is supported. It looks like you're using an older version that doesn't support the`throw` keyword.

**Comment by GetCodeHub** [comment]
> Hi, only SQL server 2012 or later is supported. It looks like you're using an older version that doesn't support the`throw` keyword.

Thank you, I will try it later.
