### ISSUE TITLE
Question about admin panel custom entity nested custom entities links to not found

### ISSUE THREAD

**Issue by ashleyNoDeal** [cofoundry-cms/cofoundry#308]
Hello ,

Sorry for confusing title . But i seem to have a issue with nested custom entities within a custom entity linking to a not found page. But the link itself uses the singular name of the custom entity. Ex ( /admin/category#/6 ). Changing category to categories would fix the problem ? is this done on purpose or do i need set a specific config option for it ?

Regards Ashley

**Comment by HeyJoel** [comment]
This is a bug, it's a simple fix and I'll see if I can push out an update over the next few days.

**Comment by ashleyNoDeal** [comment]
Thank you . Do you guys take in pull requests ?

**Comment by HeyJoel** [comment]
This is fixed and will be release in v6.1 which I'll try and get done tomorrow. If you need a fix now you can use the pre-release version on our [MyGet](https://myget.org/gallery/cofoundry) feed.

@ashleyNoDeal with regards to pull requests, we're not able to accept them *yet*, but we're in the process of arranging the CLA and securing the funding that will allow us to open up for contributions and I'm hoping to be able to announce something soon.
