### ISSUE TITLE
Admin panel: Add field/picker for date and time

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#311]
You can use the `[Date]` attribute to annotate a `DateTime` or `DateTimeOffset` property to get a date picker in the admin panel. There needs to be a separate annotation for `[Time]` and `[DateAndTime]` with one of these options being the default for these data types - probably just a date picker?

**Comment by alishajain7** [comment]
Hey Joel, Do we have any workaround for this. Time is one imp property for one of the custom entity.

**Comment by HeyJoel** [comment]
The only workaround would be to take a string value, which isn't a very good workaround. You could also develop the time control yourself, but that's not easy to do and is undocumented. For inspiration you might want to look t one of the plugins that injects a new attribute/property editor such as the [YouTube plugin](https://github.com/cofoundry-cms/Cofoundry.Plugins.YouTube)

**Comment by HeyJoel** [comment]
Fixed, will be published in 0.9. This includes a breaking change, as the `[Date]` annotationis now timezone insensitive. If you are using the `[Date]` annotation you will need to replace it with `[DateLocal]` to achieve the same functionality.
