### ISSUE TITLE
Page Templates not registering

### ISSUE THREAD

**Issue by mcockrellsana** [cofoundry-cms/cofoundry#319]
Hello,

I'm trying to add page templates to the CMS via convention described in https://www.cofoundry.org/docs/content-management/page-templates.

However, I've noticed they are not registering at all... my normal _Layout.cshtml file is working correctly, mapping the default 404 page that shows up when browsing the front end site.

I've placed the _Home.cshtml template inside my .net core 2.2 Website under `Cofoundry/PageTemplates/_Home.cshtml`  but no matter what i do, recompile, restart, etc.  The registration doesn't happen.

Have I missed a critical step in getting this template to register with the system?

**Comment by mcockrellsana** [comment]
I found the issue, autoupdate was set to false in configuration.  I'm going to close this, user error!

**Comment by NiiAnyetei** [comment]
Hello, please I need help with an update exception "Cofoundry.Domain.PageTemplateRegistrationException: Duplicate template region 'Subtitle | What We Do' in template /Cofoundry/PageTemplates/_Home.cshtml". This happened when I removed a region on the Home page and created a new database. I checked the database and it updates PageTemplateRegion with previously defined regions.
