### ISSUE TITLE
Question about editable properties on layout

### ISSUE THREAD

**Issue by mcockrellsana** [cofoundry-cms/cofoundry#322]
Hey Joel,

In your opinion what is the best method to allow, say an editable navigation menu on the layout file for views.  I thought about making specific page types have a property called "ShowInNavigation" - but this seems a little counter intuitive, also the ordering of said links when output would not be completely controllable without a lot of extra work involved. 

Unless there is already some specific functionality included in the CMS for this, my first thought was to make a new admin module section that simply allowed the selecting/adding of pages to include in the main navigation and allow drag/drop or up/down (ui) ordering.

**Comment by mcockrellsana** [comment]
I inadvertently found this issue which is somewhat related:
https://github.com/cofoundry-cms/cofoundry/issues/141

However, how would this apply to layout views?  How would you retrieve this data and be able to apply it in the layout context?

**Comment by HeyJoel** [comment]
The [Cofoundry.Samples.Menu](https://github.com/cofoundry-cms/Cofoundry.Samples.Menus) sample project shows how to do this via a [ViewComponent](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) which you can reference from any view file, including layout files.
