### ISSUE TITLE
Toolbar isn't found in TestSite

### ISSUE THREAD

**Issue by hishamco** [cofoundry-cms/cofoundry#326]
While I'm put my fingers on TestSite I got the following exception: 

**ViewNotFoundException: View not found '/Admin/Modules/VisualEditor/MVC/Views/Toolbar.cshtml'**

**Comment by HeyJoel** [comment]
Which test site are you using? One of the samples? Or a new project you have created?

**Comment by hishamco** [comment]
The one on the sample named **Cofoundry.BasicTestSite**

**Comment by HeyJoel** [comment]
I'll see if I can run some tests from a fresh repo tonight. What's your OS? It could be a file path casing issue.

**Comment by hishamco** [comment]
Windows 10

**Comment by HeyJoel** [comment]
I've tested the following on my local windows 10 installation and .NET Core 2.2:

1. Clone the [cofoundry](https://github.com/cofoundry-cms/cofoundry) repo
2. Create a new database on my local SQlserver installation named `Cofoundry.BasicTestSite`
3. Run the site
4. Navigate to /admin and complete the setup
5. Login
6. Navigate to `/admin/pages#/new` and fill in details to create a new page using the generic template
7. Click on the *Save draft & edit content* button
8. Notice that the page navigates correctly to the new page and th evisual editor toolbar is displayed

This works fine for me, but if you have adapted any configuration, made any alterations to the code or are using a pre-release version of .NET Core 3.0 then it would be good to mention that.

**Comment by HeyJoel** [comment]
Cannot reproduce this, let me know if you have any more info to add.
