### ISSUE TITLE
How to customize the admin panel screen and sidebar menu?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#329]
Hi,
 I  did sample application develope in asp.net core also implement cofoundry cms but tried customize adminpanel design for example sidebar menu for our requirement I can't do this any possible way is there?
Also I created different user based on role and permission, but I can't set password on created new users
can you please help me on this.
Thanks
 Ram

**Comment by HeyJoel** [comment]
1) There's currently no support for changing the admin panel styling unless you want to dig into the source and re-compile.

2) New users get sent an email with a temporary password they can change at first login. You may not have set up email yet; there's currently an [open issue](https://github.com/cofoundry-cms/cofoundry/issues/301) for better documentation on how to set up different email providers.

**Comment by ramkrish3020** [comment]
Thanks for your help.
