### ISSUE TITLE
Way to disable Html Sanitizer on RawHtmlDataModel Region/Blocks

### ISSUE THREAD

**Issue by mcockrellsana** [cofoundry-cms/cofoundry#330]
Hey Joel,

We have an issue where we are using template regions with an allowed block type of RawHtmlDataModel.  The issue that is present is, we've stopped tinyMCE from removing specific tags or code by supplying a configuration, but on the end result, things are still getting stripped away (iframe for videos from youtube, custom javascript carousels, etc).  

I was hoping there might be a way to completely disable the HtmlSanitizer that's included in cofoundry?  If the only way is to use my own data model and Html property and not sanitize it, that might be an issue, as we would lose the current data when we update the template/model.  I would just simply like to disable the HtmlSanitizer or tell it to allow everything at the moment.

Thoughts?

**Comment by HeyJoel** [comment]
You can [change the default HtmlSanitizer ruleset](https://www.cofoundry.org/docs/framework/html-sanitizer#changing-the-default-ruleset), but be aware that this will apply anywhere you're using the sanitizer to remove bad code from user input.

Alternatively you should be able to override the Cofoundry RawHtml template by placing a view file in the exact same location in your local solution - local resources are always picked up ahead of resources embedded in assemblies. You can copy the source of the file [here](https://github.com/cofoundry-cms/cofoundry/blob/master/src/Cofoundry.Web/PageBlockTypes/RawHtml/RawHtml.cshtml) and the location you need to put it is `/PageBlockTypes/RawHtml/RawHtml.cshtml`

**Comment by mcockrellsana** [comment]
Cool, thank you!  I didn't even think about overriding the view which is where the sanitize action is taking place, but i've placed the file in `/Views/PageBlockTypes/RawHtml/RawHtml.cshtml` and i'm getting a debug assert stating that there is a duplicate template for RawHtml, does this have to actually sit outside the Views folder in the path you described to work correctly?

**Comment by mcockrellsana** [comment]
I tried also placing the file in /PageBlockTypes/RawHtml/RawHtml.cshtml and copying the code inside just now and am receiving the error:

`FileNotFoundException: Page block type view file 'Document' not found.

Cofoundry.Domain.GetPageBlockTypeFileDetailsByFileNameQueryHandler.ExecuteAsync(GetPageBlockTypeFileDetailsByFileNameQuery query, IExecutionContext executionContext) in GetPageBlockTypeFileDetailsByFileNameQueryHandler.cs, line 49`  

Not sure if overiding with local resources is working correctly, or I'm just setting this up wrong

**Comment by HeyJoel** [comment]
`/PageBlockTypes/RawHtml/RawHtml.cshtml` should be the correct path. The exception with the Document page block is unexpected as it has nothing to do with the RawHtml page block, so I'll have to look into that and see if I can reproduce it when I get some time.

**Comment by HeyJoel** [comment]
The `FileNotFoundException: Page block type view file 'Document' not found.` bug is fixed and will be released in 0.9. Directories weren't being composed and so the files in the directory of the overridden file was being ignored.

Sorry it took so long to get around to looking at this one.
