### ISSUE TITLE
How to Add collection text?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#331]
I tried to add collection text for example ImageCollection.Can you help me on this.
Thanks
 Ram

**Comment by HeyJoel** [comment]
Hi, I'm not sure what you're asking for here, could you please elaborate or give and example of what you are trying to achieve?

Perhaps you mean you want to add a list of text items? There's no annotation for that yet, but as a work around you can use [nested data model collection](https://www.cofoundry.org/blog/14/introducing-nested-data-models) to achieve the same thing

**Comment by HeyJoel** [comment]
Closing, not enough info.
