### ISSUE TITLE
How to Create Sub menu for admin panel?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#332]
![Untitled](https://user-images.githubusercontent.com/20699474/62107326-01cca100-b2c5-11e9-8a16-d27345cf4a68.png)

I tried to add submenu but I can't do this I attached my design screen shot for can you please go through this.Is it possible here.

**Comment by HeyJoel** [comment]
Sub-menus are not possible at this time.

**Comment by ramkrish3020** [comment]
okay thanks

**Comment by HeyJoel** [comment]
I've referenced this requirement in #160 so will close this one.
