### ISSUE TITLE
Is it possible to expand and collapse option in  admin panel pages or customentity model ? 

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#333]
![image](https://user-images.githubusercontent.com/20699474/62117248-34809480-b2d9-11e9-8fa4-d8d61f1d858a.png)

The above image highlighted place for expand and collapse option is it possible?

For Example State expand inside of list of cities.

Thanks
 Ram

**Comment by ramkrish3020** [comment]
@HeyJoel  can you please help me on this

**Comment by HeyJoel** [comment]
Do you mean hierarchical data structures or allowing you to see the details view nested inline in the row?

Neither is possible, but it would be good to clarify exactly what you're looking for.

**Comment by ramkrish3020** [comment]
Yes , I am asking hierarchical data structure

**Comment by ramkrish3020** [comment]
Hi
  Can you please help me on this

**Comment by HeyJoel** [comment]
So, you could model a state custom entity with a property for a collection of city custom entities using the `[CustomEntityCollection]` attribute, but that won't display in the way you suggest in your screenshot.

Take a look at the documentation for [custom entities](https://www.cofoundry.org/docs/content-management/custom-entities) for more info on that.
