### ISSUE TITLE
Reset Password mail not sent? 

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#334]
I tried reset password in my localhost but mail not sent.can you please help me on this. I got mail template App-Data folder > Email.

From: auto@cofoundry.org
Date: Tue, 30 Jul 2019 18:39:18 +0530
Subject: Demo: Password reset request
Message-Id: <YOAAYRF168U4.EUES894L8HD6@localhost.localdomain>
To: Ram K <ramkrish3020@gmail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-98Oo4eYolhJIrpbDfdMgcQ=="

--=-98Oo4eYolhJIrpbDfdMgcQ==
Content-Type: text/plain; charset=utf-8

Hi Ram,

We have received a request to reset the password for your account on the Demo site. You can reset your password by visiting https://localhost:5001/admin/auth/reset-password?i=bbf93708ca2d40a38b34983c1e71e674&amp;t=ZDCDdfE%2Bb38Emyk5bd%2FRlmKe5JuKNOKbojRcSx4jh8EPbNMjK7EvhQVb and following the instructions.

This message was automatically generated by the Demo site.
--=-98Oo4eYolhJIrpbDfdMgcQ==
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>

<html>
<body>
    

<h2>Hi Ram</h2>

<p>
We have received a request to reset the password for your account on 
the Demo site. To do this click the following link:
</p>

<p>
    <a href="https://localhost:5001/admin/auth/reset-password?i=bbf93708ca2d40a38b34983c1e71e674&amp;t=ZDCDdfE%2Bb38Emyk5bd%2FRlmKe5JuKNOKbojRcSx4jh8EPbNMjK7EvhQVb">Reset Password</a>
</p>

<p>
    This message was automatically generated by the Demo site.
</p>
</body>
</html>
--=-98Oo4eYolhJIrpbDfdMgcQ==--

**Comment by HeyJoel** [comment]
Because there's no standard way to send an email in .NET Core we don't include a default implementation in the base package, so it's a decision you have to make as to how you'd like to send email. 

See [issue #301](https://github.com/cofoundry-cms/cofoundry/issues/301#issuecomment-490432072) for setting up email via a plugin.
