### ISSUE TITLE
Grouping CustomEntityDataModels

### ISSUE THREAD

**Issue by markchilton** [cofoundry-cms/cofoundry#343]
Hi guys

This is a question rather than an issue.

In the CMS is there a way to group CustomEntityDataModels in the menu on the left? Rather than each customentity appearing as a separate top level menu item?

So that I can have a submenu of different customEntityDataModels

Thanks
Mark

**Comment by HeyJoel** [comment]
It's not possible at this moment, but it's related to issue #160 and so I've referenced this issue from there and will close this one.
