### ISSUE TITLE
Data model annotations for image size are ignored when uploading image during a page edit

### ISSUE THREAD

**Issue by purplepiranha** [cofoundry-cms/cofoundry#344]
When editing a page, if you add an image that has already been uploaded via the images section, then you are only allowed to select the correct size (as defined by data annotations).

If you decide whilst editing the page to upload a new image, then the data annotations are ignored and any size of image can be uploaded and added to the page.

**Comment by HeyJoel** [comment]
Fixed, will be released in 0.8.1. As well as validating this on upload, the size requirements are also annotated at the top of the upload page.
