### ISSUE TITLE
How to bulkupload image in cofoundry?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#345]
Hi,
  I trying to upload  one click multiple images, @HeyJoel Can you please help me on this any possible way is there.

**Comment by ramkrish3020** [comment]
@HeyJoel Can you please help me on this.

**Comment by HeyJoel** [comment]
This is a duplicate of #7. Please don't @ me telling me to hurry up on on issues, I don't always have time to respond. The project is open source and if you're in a hurry there's plenty of opportunity for you to dig in yourself and find out if the feature is supported.
