### ISSUE TITLE
How to Validates a maximum and minimum number of items in Custom Entities?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#349]
Hi

My Question How to Validates a maximum and minimum number of items in Custom Entities Creation?

For Example the NestedDataModelCollection validate maximum and minium number of item restriction. 
![image](https://user-images.githubusercontent.com/20699474/65323536-3a9f3d00-dbc7-11e9-9bee-e5a67538c6f8.png)

Is it also possible in CustomEntity Creation?

**Comment by HeyJoel** [comment]
Hi! So, for example, if I had a "Blog Category" custom entity, you'd want to restrict it so you had between 2-10 categories (for example)?

That's not a current feature. I can't think of a good use-case for that, especially a minimum number - do you have a good example use-case?
