### ISSUE TITLE
Custom Entity Select List only show the  21 Values?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#350]
Hi,

  [CustomEntity(ManageCityDefinition.DefinitionCode)]
        public int CountryName { get; set; }

This my code I have 42 City but the selected list only showing 21 City any restriction on this issue.Can you help me on this.
please see below screen I have two page and 42 City 
![image](https://user-images.githubusercontent.com/20699474/65527609-8d9f2a00-df10-11e9-94f7-c06792db555c.png)
but this selected list dropdown showed 21 City.
![image](https://user-images.githubusercontent.com/20699474/65527758-d35bf280-df10-11e9-872d-f9eda2deca1f.png)

**Comment by HeyJoel** [comment]
The select list is filterable and does not support paging yet, see issue #280
