### ISSUE TITLE
How to remove required field for Document and Image?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#351]
Hi,

 I tried remove required field Document and Image, I searching the Cofoundry document for this but I can't find any possible solution is it possible?

![image](https://user-images.githubusercontent.com/20699474/65690623-1ba01f80-e08d-11e9-94d8-d68c35485a95.png)

**Comment by HeyJoel** [comment]
If you change the type of the property to be a nullable int, it will automatically know that it is not required e.g.

```csharp
[Image]
public int? MyOptionalImageAssetId { get; set; }
```

**Comment by ramkrish3020** [comment]
okay thanks for your quick response

**Comment by HeyJoel** [comment]
This is now in the [docs](https://www.cofoundry.org/docs/content-management/data-model-annotations/document)
