### ISSUE TITLE
Emoji picker in metadata fields

### ISSUE THREAD

**Issue by rcp87** [cofoundry-cms/cofoundry#353]
Hi,

I would like to question about the possibility of inserting an emoji picker in Title and Metadata fields for SEO reasons. 
I have seen a npm package to insert the emoji picker in a simple way with pure JS. But I don't know if I can inject some JS code in admin pages in some way or something like that.
Do you know if there is a way to do this, in a less painful way?
Thank you.

**Comment by HeyJoel** [comment]
There's no way to override elements of the admin panel at present. 

I'm not sure about other OS's but on windows 10 you can press *ctrl+.* to show an emoji picker.

**Comment by rcp87** [comment]
Ok, i supossed so. I close the issue, thank you!
