### ISSUE TITLE
Session loss

### ISSUE THREAD

**Issue by alpaor** [cofoundry-cms/cofoundry#354]
Hi, I have a problem on Cofoundry admin panel. 
When I try to add a custom entity by browsing the admin panel, website shows me a login popup and I cannot login in. It seems as if I lost the connection.

![Capture](https://user-images.githubusercontent.com/57179038/67855634-14988100-fb13-11e9-9bc7-1d93d5bfb45b.PNG)

After if I refresh the page, it redirect me to cofoundry admin panel login. 

I tried it in Chrome, Firefox and IE and the result was the same. 
Can you help me please?

**Comment by HeyJoel** [comment]
That modal is not part of Cofoundry and I expect it is being initiated from your web server.

- is this in dev or deployment? 
- Have you configured an alternate authentication mechanism - e.g. basic authentication in IIS? 
- Are you using .NET Core 2.2?
- is this a new site or an existing deployment?

**Comment by alpaor** [comment]
Ok thank you. 
I tried to configure it, but there was nothing that solve it. Is my first web page in this technology and I dont know any host that accept it. Can you recommend me a host please? 

Thank you very much!

**Comment by HeyJoel** [comment]
Hosting with Azure is usually a safe bet or any other environment that you have full control over. I've also had Cofoundry installed with cheap shared hosting, but those environments can be restrictive and can be difficult to troubleshoot issues, this is the case for hosting any ASP.NET/Core site and isn't specific to Cofoundry; it helps to be familiar with the quirks of IIS hosting for these types of deployments.
