### ISSUE TITLE
Migrate / fork to support .Net Core 3.1

### ISSUE THREAD

**Issue by sysiler** [cofoundry-cms/cofoundry#360]
Since **.Net Core 3.1 (LTS)** is out I was wondering whether Cofoundry will be updated to support it, and if so, is there already a timeframe for that? 
Anything we could do to support this migration?

**Comment by HeyJoel** [comment]
Hi there, we do intend to work on this soon and will work on it after the 6.2 release is out. I'm expecting a fair bit of work to do as 3.1 brings some big changes under the covers, particularly around endpoint routing.

**Comment by hades200082** [comment]
I was looking at this as one of the very few viable .Net Core CMS frameworks out there at the moment but without 3.1 support, it's a really hard sell for me ... why would I start a new project now on an older version?

**Comment by unixwitch** [comment]
from what i can tell, Cofoundry currently requires .NET Core 2.2, which is end of life, and doesn't work on any of the currently supported versions: 2.1, 3.1 or 5.0-preview.  did i miss anything here?  if not, that's a shame, because i like the look of Cofoundry but requiring an insecure/unsupported version of .NET makes it a non-starter for us...

**Comment by HeyJoel** [comment]
You can drop back to [v0.5.1](https://github.com/cofoundry-cms/cofoundry/releases/tag/v0.5.1) for .NET Core 2.1 support. As mentioned above, 3.1 is in the pipeline, but unfortunately my paid work no longer involves Cofoundry and so development is currently relegated to a couple of spare hours at weekends. I hope to change that at some point soon, but time keeps marching on...

**Comment by HeyJoel** [comment]
[.NET Core 3.1 is now supported in the 0.7 release](https://www.cofoundry.org/blog/23/cofoundry-0-7-released-net-core-3-1-and-a-new-imaging-plugin)
