### ISSUE TITLE
Unable to edit custom entity without publish permission

### ISSUE THREAD

**Issue by mhelala2** [cofoundry-cms/cofoundry#363]
I've noticed that the Edit button is not visible for custom entities in the admin unless I have publish permission for the entity. I would have expected to see the Edit button if I have update permission for the custom entity.

I had a quick look at the code and it looks like the issue might be here:
https://github.com/cofoundry-cms/cofoundry/blob/0818e5990c1a98a570f62fb480ab8884609b3007/src/Cofoundry.Web.Admin/Admin/Modules/CustomEntities/Content/js/customentities.js#L245

I assume the permission code in the above should be 'COMUPD' instead.

**Comment by HeyJoel** [comment]
That does look like the issue. I'll have to double check to make sure it wasn't deliberate, however it does look like a copy paste error from the original implementation.

**Comment by HeyJoel** [comment]
Fixed, this will be released in 0.6.2.
