### ISSUE TITLE
Forgot Login Password - Reset Password

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#366]
After setting up a project I tried the "forgot password" link on the login view. 
1. Fill in with email 
2. A .txt file is created in App_Data/Emails with a reset link inside
3. Clicking this link returns a page with : "Invalid password reset request"

I'm guessing this requires further config to make it work. How do I set this up? I couldn't find much related to this in the documentation. 

Thanks.

**Comment by HeyJoel** [comment]
There's two parts to this

1) If you don't install an email plugin, the email will go to a debug directory in App_Data, as you have found. To set up email, install one of the [Cofoundry plugins](https://www.cofoundry.org/docs/plugins/available-plugins) for email, e.g. [SendGrid](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.SendGrid) or [MailKit](https://github.com/cofoundry-cms/Cofoundry.Plugins.Mail.MailKit).

2) If you're copy and pasting the link from the html part of the debug email, the link will be html attribute encoded, so you'll need to replace tings like `&amp;` with `&`.

**Comment by HeyJoel** [comment]
I did notice that the plain text portion of the email is also html encoded, which isn't right. I'll get that fixed.

**Comment by endrehegyi** [comment]
In the documentation it states that "By referencing this package your Cofoundry project will automatically replace the default IMailDispatchService implementation with one that uses SendGrid". So I added the SendGrid Nuget package to my project. I then added the following config to my appsettings.json : 
```
"Cofoundry": {
    "Database": {
      "ConnectionString": "my db con string"
    },
    "Mail":{
      "SendMode": "Send",
      "DefaultFromAddress": "my email address"
    },
    "Plugins":{
      "SendGrid":{
        "ApiKey":"my API key from SendGrid"
      }
    }
  }
```
The values have been changed to avoid exposing my details.

This doesn't seem to work, SendGrid doesn't get used and no email is sent - only saved to local AppData like before. 

Could you suggest anything or point me in a direction to fix this ?

**Comment by HeyJoel** [comment]
That looks to be the correct usage. If your application is still using local drop then I expect the "Cofoundry:Mail:SendMode" config setting isn't being applied properly. Are you sure the config is being applied correctly? To test this in your debug environment, try injecting `MailSettings` into a class and inspect the values.
