### ISSUE TITLE
Porting content between instances

### ISSUE THREAD

**Issue by hhgm** [cofoundry-cms/cofoundry#367]
Hi, I am new to Cofoundtry so forgive me if I have not found the correct way around this lovely tool.

I have started building a site in Cofoundry, but I am feeling the pain of deploying pages and other content I have set up in my development instance. Is there a way of extracting this and porting it to a test/production instance?

**Comment by HeyJoel** [comment]
The only way to do this currently is to backup and restore the database between environments. There's no automated sync.
