### ISSUE TITLE
Disable visual editor frame on static pages

### ISSUE THREAD

**Issue by adamket** [cofoundry-cms/cofoundry#371]
I'm attempting to integrate Cofoundry into nopCommerce and seeing an issue where all response js object properties are converted to camel-case, which is causing issues on certain pages, particularly those with DataTables.  

Is there a simple way to disable the editor widget on what Cofoundry considers static pages, or would this be an enhancement?

Thanks!

**Comment by HeyJoel** [comment]
You can selectively disable the visual editor by implementing a class that inherits from `IVisualEditorRequestExclusionRule`, the DI system will automatically pick it up. For an example you can use the [DefaultVisualEditorRequestExclusionRule](https://github.com/cofoundry-cms/cofoundry/blob/master/src/Cofoundry.Web.Admin/Admin/Modules/VisualEditor/Framework/DefaultVisualEditorRequestExclusionRule.cs) in Cofoundry.

However, it sounds like the problem you are having is with the default JsonSerializer settings. I've not used nopCommerce, but Cofoundry expects lower camel case, and it sounds like nopCommerce is expecting upper camel case.

If you want to change the MVC json serlializer settings you could override the default `IMvcJsonOptionsConfiguration` (see [CofoundryMvcJsonOptionsConfiguration](https://github.com/cofoundry-cms/cofoundry/blob/1a45165dc499c66690b4b3660a26b664c8e8e0f9/src/Cofoundry.Web/App_Start/StartupTasks/ServiceConfigurationTasks/CofoundryMvcJsonOptionsConfiguration.cs) for existing implementation), but I'm not sure the Cofoundry panel will work correctly with upper-camel case property names - I seem to remember doing some work on that but haven't got time to try it out right now.

**Comment by adamket** [comment]
nopCommerce doesn't transform json properties at all by default.  I've found a work-around for the dataTables implementation, and have overridden the DefaultVisualEditorRequestExclusionRule to hide the editor while in nop's back-end admin.  

Thanks kindly!
