### ISSUE TITLE
Visual Editor does not load when Application Insights is configured

### ISSUE THREAD

**Issue by johanosventer** [cofoundry-cms/cofoundry#373]
The `/admin/Admin/Modules/VisualEditor/Content/js/visualeditor_min` is not requested from the front-end if the Azure App Insights SDK is also loaded at the same time.

Disabling Azure App Insights from the Azure Portal resolves the issue.

Happens for both the dotnetcore 2.1 and dotnetcore 3.1 nuget packages

**Comment by HeyJoel** [comment]
Hi sorry for not getting back to you. I've seen this before in 2.1 and it seemed to be an issue with App Insights mangling the html after we'd automatically added our js. I couldn't see an easy way to resolve it at the time and may require a manual approach to adding either our or the App Insights scripts.

**Comment by HeyJoel** [comment]
Fixed, will be released in 0.9.
