### ISSUE TITLE
Is this cms supports CKEditor

### ISSUE THREAD

**Issue by SAISUDHEERREDDY** [cofoundry-cms/cofoundry#374]
Is this cms supports CKEditor?

**Comment by HeyJoel** [comment]
CKEditor is not supported. You could build a plugin for it, but we don't have documentation on how you would do that right now. Something like the [Vimeo plugin](https://github.com/cofoundry-cms/Cofoundry.Plugins.Vimeo) might be a good place to start if you wanted to do this.
