### ISSUE TITLE
Background Tasks within Plugins

### ISSUE THREAD

**Issue by purplepiranha** [cofoundry-cms/cofoundry#375]
I'm sure I'm probably doing something wrong here but...

I'm trying to implement a background task to import an Instagram feed. The idea is to update the database from the feed every few minutes, so that it can be displayed without having to hit Instagram's API on each page refresh.

Having looked at the docs, and the `AssetFileCleanupTask` in `Cofoundry.Domain`, it looked quite simple. I added the Nuget package for `Cofoundry.Plugins.BackgroundTasks.Hangfire` to my `MyProject.Web project`, verified that it the cleanup task was running and then got to coding my own task (in `MyProject.Plugins.Instagram` project).

```
public class InstagramFeedImportBackgroundTask : IAsyncRecurringBackgroundTask
    {
        private readonly ICommandExecutor _commandExecutor;
        private readonly IExecutionContextFactory _executionContextFactory;
        private readonly ILogger _logger;

        public InstagramFeedImportBackgroundTask(
            ICommandExecutor commandExecutor,
            IExecutionContextFactory executionContextFactory,
            ILogger<InstagramFeedImportBackgroundTask> logger
            )
        {
            _commandExecutor = commandExecutor;
            _executionContextFactory = executionContextFactory;
            _logger = logger;
        }

        public async Task ExecuteAsync()
        {
            _logger.LogInformation("Recurring Task Start");
            var executionContext = await _executionContextFactory.CreateSystemUserExecutionContextAsync();
            var instagramFeedImportCommand = new InstagramFeedImportCommand();
            await _commandExecutor.ExecuteAsync(instagramFeedImportCommand, executionContext);
            _logger.LogInformation("Recurring Task End");
        }
    }
```

```
public class InstagramSettings : CofoundryConfigurationSettingsBase
    {
        /// <summary>
        /// How often the background task should run, measured in minutes.
        /// </summary>
        public int BackgroundTaskFrequencyInMinutes { get; set; } = 5;
    }
```

```
public class InstagramFeedBackgroundTaskRegistration : IBackgroundTaskRegistration
    {
        private readonly InstagramSettings _instagramSettings;


        public InstagramFeedBackgroundTaskRegistration(
            InstagramSettings instagramSettings
            )
        {
            _instagramSettings = instagramSettings;
        }

        public void Register(IBackgroundTaskScheduler scheduler)
        {
            scheduler.RegisterAsyncRecurringTask<InstagramFeedImportBackgroundTask>(_instagramSettings.BackgroundTaskFrequencyInMinutes);
        }
    }

```

When I then run this and look at the Hangfire dashboard I get the following:
![image](https://user-images.githubusercontent.com/15064668/91067031-50fd1680-e62a-11ea-924f-f539b0585453.png)

Then after a few seconds, the job is deleted.

Visual Studio output window shows the following: `Hangfire.Server.RecurringJobScheduler: Debug: Recurring job 'MyProject.Plugins.Instagram.Domain.BackgroundTasks.InstagramFeedImportBackgroundTask' doesn't exist and will be removed from schedule.`

Any ideas would be much appreciated. Thanks.

**Comment by HeyJoel** [comment]
The code looks right, but I'm not sure why it's not working. If the tasks throws an error you should see it in the jobs log in the dashboard (I think it's under "jobs" and then you have to filter to find jobs with errors). Have you tried stepping through the background task to see if it's being run / throwing an error?

**Comment by purplepiranha** [comment]
Hi Joel, thanks for your quick reply.

It didn't appear anywhere in the Jobs page. The Asset FileCleanup job showed there under Successful, but there was nothing under 'Failed'.

I have however, finally, worked out what's causing it to fail!

It appears that when the `Namespace.ClassName` for the background task goes over 86 characters in length it fails. I'm guessing this must be a HangFire limitation. 

For me, renaming `InstagramFeedImportBackgroundTask` to `InstagramImportBackgroundTask` seems to have done the trick.

**Comment by HeyJoel** [comment]
Oh right, well that's a new one for me, and I am quite partial to long/informative class names. 

It must be a HangFire limitation, as we don't save the background task class name anywhere. Thanks for posting the answer.
