### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by matthewdamon** [cofoundry-cms/cofoundry#376]
I'm currently building a site with cofoundry, and I'm noticing cofoundry.org is down.  Is this a long-term issue?  I rely on this site for its (typically awesome) documentation.  It appears the domain expired.  https://www.cofoundry.org

Thanks for any ETA on when the site will be live again.

**Comment by HeyJoel** [comment]
Hi there, it's back up and running now, it was an SSL cert issue. Thanks for letting us know.

**Comment by matthewdamon** [comment]
@HeyJoel , I'm still seeing the issue:
![image](https://user-images.githubusercontent.com/71155918/92999919-70c98100-f4ea-11ea-9529-c8b864dcfea3.png)

**Comment by matthewdamon** [comment]
@HeyJoel , I'm still seeing the issue:
![image](https://user-images.githubusercontent.com/71155918/92999970-bf771b00-f4ea-11ea-96cc-cb2437dc098c.png)

**Comment by HeyJoel** [comment]
Er sorry! It's proper fixed now. Thanks again for letting us know.

**Comment by matthewdamon** [comment]
Perfect, thanks!
