### ISSUE TITLE
TinyMCE source editor

### ISSUE THREAD

**Issue by adamket** [cofoundry-cms/cofoundry#377]
Minor enhancement request:

It'd be helpful if the default Cofoundry TinyMCE source editor were mono-space font.

I'm aware you can use custom TinyMCE configuration, though it appears you lose the integrated component for uploading images.  Is there a  workaround?

 Also the TinyMCE Full screen option appears to have an issue.

Finding lots of good use for your product overall,
Thanks!

**Comment by HeyJoel** [comment]
How are you supplying the config? The button code for the image upload is `cfimage`, so if you include that then the button should appear.

**Comment by HeyJoel** [comment]
In 0.9:

* code editor now has monospaced font
* Position bug with full-screen in a moal fixed.

There's also an issue with the height not being properly set by TinyMCE, but that will have to be fixed as part of a later UI refresh and/or upgrade to TinyMCE.
