### ISSUE TITLE
grunt-install fails

### ISSUE THREAD

**Issue by MichalGrzegorzak** [cofoundry-cms/cofoundry#378]
Hi,
I was trying to run grunt, but it fails on install. Can someone help please?

Trace:
C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build>grunt-install.bat

C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build>npm install --save-dev

> gifsicle@0.1.7 postinstall C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\gifsicle
> node index.js

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:744:5)
    at C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\download\index.js:35:43
    at each (C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\download\index.js:33:5)
    at C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\bin-wrapper\index.js:108:20
    at C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\bin-wrapper\index.js:141:24
    at C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\bin-check\index.js:30:20
    at C:\projects\__cms\cofoundry-master\src\Cofoundry.Web.Admin\Build\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by stephenthornton** [comment]
Hi @MichalGrzegorzak - at first glance this looks like a node version issue. What version are you running?

**Comment by MichalGrzegorzak** [comment]
@stephenthornton - I'm on Node v10.16.0

**Comment by stephenthornton** [comment]
@MichalGrzegorzak - i have been able to replicate the errors you have. You should still be able to run the grunt-watch.bat file regardless of these and compile css/js changes. 

This is quite an old setup and certainly something we have on our radar to update to a more modern workflow. To remove the errors you can always manually update your packages my running `npm audit fix --force` inside the /build folder. I have done this after testing your scenario and it's cleared all errors.

Hope this works for you.

**Comment by MichalGrzegorzak** [comment]
@stephenthornton - thank you, it works!
