### ISSUE TITLE
Is this project still sponsored?

### ISSUE THREAD

**Issue by tommymh** [cofoundry-cms/cofoundry#384]
I noticed the link to the sponsoring company is dead now.  Just curious, as it's always nice to have some kind of backing to ensure continuity of the project, while picking a CMS.

**Comment by HeyJoel** [comment]
The old sponsor is no more and I haven't had time to update it. We have a new potential sponsor but we're yet to see in what capacity that ends up being. Last year's attempt at picking up a sponsor didn't work out, hence the lack of progress. 

As you say, it's always nice to have some kind of backing, but it's a rare thing to find.

I don't want to speak too soon about something that might not happen so you'll see an update when the situation is more certain.

**Comment by HeyJoel** [comment]
Existing sponsor links have now been removed from the site and the readme. More clarification will come in time when we have it.
