### ISSUE TITLE
Page loading performance problem

### ISSUE THREAD

**Issue by ernestoSerra** [cofoundry-cms/cofoundry#398]
Hi, we are having problems loading the main page of our website. 
We have used the miniprofiler extension to detect the problem and it indicates that it is in the controller that requests the content of the page. 

![image](https://user-images.githubusercontent.com/8802992/104935575-af48de00-59ab-11eb-8fd1-4d4d509acbe4.png)

We have tried to remove blocks from the page and the result improves with each block that we remove. But the problem is not of a specific block, could there be a performance problem in the load function that cofoundry uses internally?

Thanks for your help!

**Comment by HeyJoel** [comment]
Well, that's hard for me to say. The controller there is mainly executing your page, template and layout files - so it depends what you are doing in those places. I can see your layout file is also taking some time to render too.

If the performance characteristics have changed, I think you need to ask yourself what has changed in your code or data and work from there.

**Comment by HeyJoel** [comment]
No further info provided
