### ISSUE TITLE
Replace Html Editor

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#4]
The TextAngular editor has been buggy (copy/paste issues and general caret problems) and should be fixed or replaced with an alternative.

- If an alternative is used it would be good to pick something framework agnostic to make it easier to move from angular 1 to another framework (e.g. Angular 2)
- There should be a much better interface for inserting images (and uploading inline), videos, document links
- The ability to link to pages and custom entities would also be good
- It would be good to think about adding a developer extensibility point here too.

**Comment by stephenthornton** [comment]
Partially completed. HTML editor has been replaced with TinyMce. Have created new issues with extra functionality to be completed as separate jobs
