### ISSUE TITLE
Thread safety with DbContext

### ISSUE THREAD

**Issue by getsetcode** [cofoundry-cms/cofoundry#400]
Hi. I've been using Cofoundry for a couple of weeks and generally I've found it really intuitive. A far better experience than other open source CMS's I've used in the past. So thank you for the hard work that has gone into it. I have just encountered an issue though so thought I'd raise it.

I have a couple of places where I need to load content from a few sources in order to build a view model. For example, when loading a site header I need to load the image asset and also a collection of pages to build the nav. In these cases I create two or more tasks that perform the async operations of `IContentRepository` and await them all together rather than one by one in order to maximise the page load performance. 

Example code:
```
var oneTask = _contentRepository.CustomEntities().GetByIdRange(entityIds).AsRenderSummaries().ExecuteAsync();
var twoTask = _contentRepository.ImageAssets().GetById(imageId).AsRenderDetails().ExecuteAsync();

await Task.WhenAll(oneTask, twoTask);
```

I've found when using this pattern, occasionally (not always) the site blows up with the following exception:

> InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

I presume each of these async operations is re-using the same `DbContext` which I believe is inherently not thread safe. Is there a recommendation for maximising the performance of read-only operations as described above? Thanks.

**Comment by HeyJoel** [comment]
Thanks for the feedback, much appreciated. 

To be honest, I've not thought about parallel db queries, and as you note, EF doesn't support it and [advises against it](https://docs.microsoft.com/en-us/ef/core/miscellaneous/async).

If you wanted to do it you'd have to work with a new DbContext instance for each query, which has it's own overhead, although it will get it's connection from the shared pool anyway. Cofoundry uses one DbContext per request, which I believe is the recommended approach, so you'd need a new DI scope per query, which you can do by injecting the NET Core `IServiceProvider` and creating a new scope:

```csharp
using (var scope = _serviceProvider.CreateScope())
{
    var repository = scope.ServiceProvider.GetRequiredService<IDomainRepository>();

    // ...do stuff
}
```

However if using this approach you'd need to consider whether the performance benefit for one request comes at the expense of others and scalability (possibly connection pool starvation). I'm no expert here, so I'm open to ideas, but I expect overall performance benefits may be situational.

**Comment by getsetcode** [comment]
Thanks for the reply. Certainly in my case that would be overkill. I can live with syncronous operations here. Might be something worth adding to your docs though since the impact I observed locally was intermittent and could therefore be something that only hits in production. Meanwhile, looking forward to further updates to this CMS, thanks for your efforts to date.
