### ISSUE TITLE
Error: Cannot load angular-sanitize.min.js.map

### ISSUE THREAD

**Issue by jbrandt-q5** [cofoundry-cms/cofoundry#403]
I get this error in the browser console: 

DevTools failed to load SourceMap: Could not load content for https://localhost:44328/admin/Admin/Modules/Shared/Content/js/angular-sanitize.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by HeyJoel** [comment]
The error is generated by your browser dev tools because we don't have source maps for the admin JavaScript. It's safe to ignore. We won't be adding source maps for the existing admin panel.
