### ISSUE TITLE
Third party data as "Widget"

### ISSUE THREAD

**Issue by ScarlettCode** [cofoundry-cms/cofoundry#404]
Hi,

I'm looking for some guidance in what would be the best way to integrate external data into the CMS. I have some external data and I want to create "widgets" which can then be placed anywhere on any page. My current thought is to use Page Block Types. My question is can I call out to a third party api or another database from within the MapAsync method of the IPageBlockTypeDisplayModelMapper or is there a better way of doing this?

Then following on for this, if a "Widget" was user specific can I access a users logged in state and id from within the MapAsync method so I can use that to fetch the correct data for a specific user?

Thanks

**Comment by HeyJoel** [comment]
You can inject anything into your `IPageBlockTypeDisplayModelMapper ` and call anything in `MapAsync`, so yes you can call out to a service or run a custom database call. Some things to consider:

- We don't cache the result of the mapper, so you'll want to consider performance. We may implement caching at some point, but i expect it would be opt-in.
- Http services in particular can be a slow and timeout, so you'll want to consider how you cache that e.g. where we have done this with an instagram feed we have wrapped it in a cache that expires every hour or so. If you wanted to get fancier you could run a background task that updates the cache periodically so the user accessing the page doesn't take the performance hit.
- If using 3rd party service, do consider a fallback option if the service returns an error so it doesn't break your whole page. This isn't really Cofoundry specific though, just general best practice.

For accessing user state:

- If using our [CQS framework](https://www.cofoundry.org/docs/framework/data-access/cqs), the user id is included in the `IExecutionContext` parameter as part of the `IUserContext` object.
- In views you can use the [Cofoundry View Helper](https://www.cofoundry.org/docs/content-management/cofoundry-view-helper) to access user data.

For anything else, you can access user data though [`IContentRepository`](https://www.cofoundry.org/docs/content-management/accessing-data-programmatically) e.g.

```csharp
var user = _contentRepository
    .Users()
    .GetCurrent()
    .AsSummary()
    .ExecuteAsync();
```

Or inject `IUserContextService` and use that to get basic user data such as the id and go from there.
