### ISSUE TITLE
Show friendly enumeration item names

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#405]
I have a booking state enumeration `BookingStateType` and use this for a DataModel:

    [Display(Name = "Bookingstatus")]
    [SelectList(typeof(BookingStateType))]
    public BookingStateType BookingState { get; set; }

Now I would like the booking state to show up as a friendly name in the admin system, so I add Description attributes to it (in Danish) :

    public enum BookingStateType { 
      [Description("Forespørgsel")]
      Requested,

      [Description("Bekræftet")]
      Confirmed,

      [Description("Aflyst")]
      Cancelled
    }

Unfortunately the admin section still shows the code names "Requested" etc. in the selected-list.

Please look for Description attributes and their values when showing select lists (and other UI forms).

**Comment by HeyJoel** [comment]
I'm sure we can add that. For now you should be able to use [IListOptionSource](https://www.cofoundry.org/docs/content-management/data-model-annotations/selection-lists#ilistoptionsource) to generate the options with a bit more manual effort.

**Comment by HeyJoel** [comment]
Fixed, will be release in v0.10
