### ISSUE TITLE
DateTime handling

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#411]
Could you please document how `DateTime` objects are to be handled correctly?

If I enter a date in a DateTime property of a custom entity, using the admin panel, it will be stored in GMT timezone. In Denmark (timezone +1) this means that a date "2021-03-15 00:00:00" will be serialized to "2021-03-14T23:00:00.000Z" in JSON - that looks like the date before, but is not.

Loading the entity from the entity repository yields a UTC-kind `DateTime` instance which will serialize into "2021-03-14T23:00:00.000Z" again when returned as a JSON API response.

In JavaScript one might just (as I did) clip the first 10 chars to get YYYY-MM-DD for a "date" input field. Duh! Now your "March 15th" date shows up as "March 14th".

So what a developer needs to be informed of in the documentation, perhaps in a special "Working with dates" section, is that you always have to convert the `DateTime` instance into local time before showing it to the end user. This can be done either server side or client side with suitable JavaScript libraries like for instance Moment.js.

And similarly you must always convert it back to UTC-kind when storing it again, as it will otherwise be serialized into a string without timezone indication "2021-03-15T00:00:00.000", potentially causing troubles further down the line.

The definition of "local time" should be the browser's local time.

Working with timezones seriously sucks and has always done so.

**Comment by JornWildt** [comment]
Okay, my fault, as so often before. I see that I copy-pasted a [DateLocal] attribute into my data model, which means I get exactly the behavior described - as documented on https://www.cofoundry.org/docs/content-management/data-model-annotations

**Comment by JornWildt** [comment]
Found the docs in the Cofoundry code (helps a lot to have the GIT repo and VS solution local!). I think the `Date` spec is a bit odd:

> The UI picker and value is timezone insensitive i.e. UTC, with the time value always set to midnight UTC.

Why did you choose UTC-kind? There is probably a bit of Cofoundry history involved, but by the names, I would have guessed:

`DateLocal`: store dates as local dates, Local-kind, without any timezone specification. 

`Date`: would have to be the opposite of `DateLocal`, so it would be UTC-kind, most likely with browser's timezone offset.

Anyways - all things work and you have made a great job of it all. This part was just a bit confusing.

**Comment by HeyJoel** [comment]
Hi, we do have date and time docs, but it looks like I forgot to publish them in the last release - you can now find them [here](https://www.cofoundry.org/docs/content-management/data-model-annotations/dates-and-times).

So my thinking is as follows:

- `[Date]` doesn't care about the timezone, use it if you want to select a date that is not timezone dependent (e.g. a birthday), or if you are taking care of the timezone in your code (e.g. you're working in a fixed timezone).
- `[DateLocal]` is aware of the browsers timezone, but you may have many users in different timezones or you may be temporarily in another timezone (on holiday) and so to be consistent we always convert to UTC when storing it. When rendering the date out again it's your choice if you want to render it into a specific timezone, or use the timezone of the current user.

This design loosely follows the behavior of the various date and time input fields in HTML.

There is a third option that has not yet been implemented, which is a field that allows you to select the date and a timezone e.g. I have an event that starts at "2022-01-01 00:00:00" in "Pacific SA Standard Time" - this would require two fields in your data model or we could create a new type. But this can worked around by just adding another field to your data model to capture the timezone from a select list.

I didn't get around to implementing this third option yet, but it will be required when we implement the interface for setting publish dates for pages/custom entities. I wanted to think a bit more about it and also there is also an issues with cross-platform timezone code that needs resolving or accepting.

**Comment by JornWildt** [comment]
Thanks for the explanation 👍

**Comment by HeyJoel** [comment]
No worries, the feedback is appreciated.
