### ISSUE TITLE
Modular CSS and JavaScript includes

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#412]
It would be neat to have a standard way of saying "Include script/stylesheet XXX" in a razor view component. It is not possible to do using standard razor sections in partial views and view components, so something along the lines of an HTML helper is needed:

```
@Html.AddScript("~/js/script.js")
@Html.AddStylesheet("~/css/style.css")
```

and then have similar sections in the _Layout.cshtml file:

```
<head>
  @Html.IncludeStylesheetsHere()
</head>
<body>
  @Html.IncludeScriptsHere()
</body>
```

But maybe it is better to use a JS framework for it instead? For instance "Require JS"?

**Comment by HeyJoel** [comment]
This doesn't seem particularly relevant for Cofoundry. I know we have a few HTML helpers, but generally we try to leave MVC / FrontEnd up to you.If it's a feature missing from Razor then perhaps there's another package out there that can handle it?

**Comment by JornWildt** [comment]
That's fine. It is not specific for Cofoundry - though a natural consequence of building modular applications for which Cofoundry is a great helper. Could surely be made as an unrelated package.

**Comment by HeyJoel** [comment]
Closing as I think this is out of scope. Please add your thoughts if you think otherwise.
