### ISSUE TITLE
CustomEntity ID generation

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#417]
This mostly a curiosity question ... during a work session where I was adding and deleting custom entities, the custom entity ID range suddenly jumped from around 70 to 1071 - and I am pretty sure I didn't randomly add and delete 1000 custom entities. So I was wondering - how is the custom entity ID generated? I don't see an auto-increment column in the database?

**Comment by HeyJoel** [comment]
Actually, it is set up with an auto-increment id, the behavior you see if actually a performance feature of SQL 2012+, as explained in [this SO answer](https://stackoverflow.com/a/14146237/716689). 

It's something I had also noticed but hadn't looked into, so I learnt something new today =)

**Comment by JornWildt** [comment]
Thanks 👍 Then I learned something too. It fits rather well with Windows rebooting the same day.
