### ISSUE TITLE
Send Email in Cofoundry.

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#421]
Hello I'm new in cofoundry cms .I have face a issue how to send email after create a new user by admin side .Please let ne know it's possible or not .
Thanks

**Comment by HeyJoel** [comment]
Which aspect are you referring to:

1. When a user is created, an email containing a temporary password is automatically sent. To enable email to be sent via your mail host you have to install a plugin, see [mail docs](https://www.cofoundry.org/docs/framework/mail)
2. If you want to send a custom email when a Cofoundry admin user is created, there isn't a message event for that yet, this is covered in issue #281

**Comment by sunny7713** [comment]
When a user is created, an email containing a temporary password is automatically sent. To enable email to be sent via your mail host you have to install a plugin, see--- I have already install plugin but not send email

**Comment by sunny7713** [comment]
Please let me know Because it's more important for me . I have one suggestion for you please once check your side.

**Comment by sunny7713** [comment]
@HeyJoel ??

**Comment by HeyJoel** [comment]
Sorry, you're going to have to provide more information. Which plugin? How have you configured it, and are you sure your mail server configuration is correct?

**Comment by sunny7713** [comment]
Yes I'm Sure Because I have use Send Grid Plugin.

**Comment by sunny7713** [comment]
Why are you Closed this Issue .Please resolve this and provide proper solution.
Thanks

**Comment by JornWildt** [comment]
There are a lot of things that can go wrong when sending e-mails. It is not enough just to install one of the e-mail plugins. Are you sure you configured all of your e-mail settings correct and, somehow, verified that sending e-mails actually works?

You issue was closed because you didn't provide enough information for HeyJoel to have any chance of helping you.
