### ISSUE TITLE
Display Post By Categories.

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#425]
I have set  Blog Post with multiple Categories it's working fine display blog with Categories .But I face a Issue not display blog post by Categories for e.g I have click Music Categories so it's not display Music Categories Blog Post(Display All Blog Post).

Thanks

**Comment by HeyJoel** [comment]
Are you asking how to filter custom entities by a category? Neither is currently implemented:

- For filtering by tag, see issue #12 
- For filtering by a custom entity property see issue #31 

Currently you can get all custom entities and filter client side, which can be slow for large numbers of custom entities. This is mentioned in issue #318

**Comment by sourabhCofoundry** [comment]
How to filter in client side .

**Comment by sourabhCofoundry** [comment]
One more query which time are you Implement custom entities for  category.
