### ISSUE TITLE
Filter Categories By Id.

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#427]
I have make 10 Blog Post with 5 Categories It's working fine. But I have face issue not filter Blog Post by categories .Please let me know how it Working and I want to make a this type url.
https://localhost:44368/blog/category/business-blogs

**Comment by HeyJoel** [comment]
Is this a content managed page for each category? You can either

- Create a custom entity page for your category entity - [see docs here](https://www.cofoundry.org/docs/content-management/custom-entity-pages)
- If you don't need content management, so can just create a standard MVC page and pull in any data you need via [`IContentRepository`](https://www.cofoundry.org/docs/content-management/accessing-data-programmatically)

**Comment by sunny7713** [comment]
Ok .
Any live example Provide.

**Comment by HeyJoel** [comment]
On what exactly? Info on routing can be found in the docs with examples. Programatic access to data can also be found in the docs linked above.
