### ISSUE TITLE
Temp Data .

### ISSUE THREAD

**Issue by SourabhDhiman77** [cofoundry-cms/cofoundry#436]
Hello I have try to set Collection in TempData .Data is stored in TempData but I have face a issue my page is not working.
500 error display.
This is my code
 private ICollection<CategorySummary> MapCategories(PagedQueryResult<CustomEntityRenderSummary> customEntityResult)
        {
            var categories = new List<CategorySummary>(customEntityResult.Items.Count());
            try
            {
                foreach (var customEntity in customEntityResult.Items)
                {
                    var model = (CategoryDataModel)customEntity.Model;
                    var category = new CategorySummary();
                    category.CategoryId = customEntity.CustomEntityId;
                    category.Title = customEntity.Title;
                    category.ShortDescription = model.ShortDescription;
                    category.UrlSlug = customEntity.UrlSlug;

                    //category.FullPath = customEntity.PageUrls.FirstOrDefault();
                    categories.Add(category);
                    TempData["Data"] = categories;
                }
            }
            catch(Exception ex)
            {
                ex.InnerException.ToString();
            }
            
            return categories;
        }
    }
Note-Without tempdata my page is working fine.

**Comment by HeyJoel** [comment]
What is the exception? It doesn't sound like anything to do with Cofoundry - TempData is an ASP.NET concept.

**Comment by HeyJoel** [comment]
Closing - inactive and poor description of issue.
