### ISSUE TITLE
Get Page URL .

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#441]
Hello Hey Joel
I have set Properties in Model for Page Collection. This is a properties
 [Display(Name = "Pages", Description = "The pages to display, orderable by drag and drop.")]
 [PageCollection(IsOrderable = true)]
        public string Page { get; set; }

Drop Down generate with All Page collection .But I have Face a issue I want to get Page Url(/blog,/aboutUs)but Page Id is get.How to get Page Url .
 @*<div class="col-md-12 text-center">
        <button class="LearnMoreButton" type="button">@Cofoundry.Sanitizer.Sanitize(Model.PageUr.ToString())</button>
    </div>*@

**Comment by sunny7713** [comment]
@HeyJoel Is there or not ???

**Comment by HeyJoel** [comment]
I appreciate that English is probably not your first language, but your issue does not make sense, and the code excerpt is mangled.

**Comment by HeyJoel** [comment]
Closing - poor description of issue.
