### ISSUE TITLE
Custom Entity Alternative

### ISSUE THREAD

**Issue by vector-man** [cofoundry-cms/cofoundry#447]
In the documentation, you have this notice about Custom Entities: 

> Custom entities are great for many typical scenarios and have a great deal of flexibility built in, however they aren't designed to be used in all scenarios. They are not appropriate for:
>
> Complex hierarchical data models. Due to their complexity these can sometimes be more simply expressed through a custom implementation. You can still leverage the admin UI tools to build the editor interfaces.
>
> Per-user data, e.g. user profile data
>
> Log style data, e.g. contact form responses"

I'm working on an entity design that is somewhat complex (not incredibly, just a bit) and has a property to store User's data, so it looks like I'll need to to use a method other than Custom Entities. Do you have an example that doesn't use Custom Entities to store data that the backend UI can edit?

**Comment by HeyJoel** [comment]
I think it depends on what you're trying to do, but it mainly comes down to custom entiries being a single table, with custom data stored as a single json blob, so if you're trying to replicate some sort of complex heirarchy, data with large sets of dependencies, or large log-style data sets then it's not really a good solution for that.

So with that in mind, if you have a very small user set and you're happy with how the custom entity data is presented/editable in the admin panel then it may still be an acceptable choice.

In terms of user custom data issue #176 covers that.

For custom admin panel modules, as the [docs](https://www.cofoundry.org/docs/admin-panel/creating-an-admin-module) somehwat hints at, it's not in a state that i'm willing to provide documentation and support around, but if you're a little adventurous and don't mind poking around the source code you can have a go at working it out from some of the existing plugins such as [ErrorLogging](https://github.com/cofoundry-cms/Cofoundry.Plugins.ErrorLogging) or [YouTube](https://github.com/cofoundry-cms/Cofoundry.Plugins.YouTube) or the [Cofoundry.Web.Admin](https://github.com/cofoundry-cms/cofoundry/tree/master/src/Cofoundry.Web.Admin) project.

If you just want to build your own admin module in another technology and have it show up in the menu, you can just implement `IAdminModuleRegistration` which will allow you to insert a menu item and a custom link.

**Comment by vector-man** [comment]
Thanks for the reply. My data model is basically something like this:
```
Campaigns Collection (can be unlimited campaigns) 
Each Campaign Has {
    Name
    Date
    Prop1 { 
        PName
        PDate
        PUsers (Contains some of all of the users on my website) 
     }
}
```
PUsers needs to have to no maximum.

I was really hoping I could get a page for all Campaigns, to edit each, as well as a page for Prop1 to edit all of them for each Campaign, and Add/Remove each user from PUsers. So it looks like I'll need to do something custom. 

Thanks for providing some info. I'll take a look at them when I get a chance.
