### ISSUE TITLE
Paginantion 

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#448]
@HeyJoel any example for pagination in cofoundry .Please let me any example How to implement pagination in cofoundry .It's argent for me .

**Comment by JornWildt** [comment]
See https://www.cofoundry.org/docs/framework/paged-queries

**Comment by JornWildt** [comment]
If the above example doesn't fit your expectations then please describe in more details what it is you expect.

**Comment by HeyJoel** [comment]
Thank you @JornWildt 

@sourabhCofoundry I responded to #446 asking for more information, and you've just closed it and repeated the same thing here. If you want me to spend my free time helping you, you need to put some effort in to accurately descibe what it is you are trying to do, read the docs and check issues that have already been posted.

**Comment by sourabhCofoundry** [comment]
@{

        var prevDisabled = !Model.IsFirstPage() ? "disabled" : "";
        var nextDisabled = !Model.IsLastPage() ? "disabled" : "";
    }
    <a href="#" id="prev" data-Id="@(Model.PageNumber-1)" class="btn btn-primary btn-sm @prevDisabled">Previous</a>
    <a href="#" id="next" data-Id="@(Model.PageNumber+1)" class="btn btn-primary btn-sm @nextDisabled">Next</a>
I have implement this code for next and previous it's only 2 page display .

**Comment by sourabhCofoundry** [comment]
I have use this code for pagination   [Obsolete]
        public async Task<IViewComponentResult> InvokeAsync()
        {      //HttpContext.Request.
            //var query = new SearchCustomEntityRenderSummariesQuery()
            //{
            //    CustomEntityDefinitionCode = "EXMPLE",
            //    PageSize = 40,
            //    PageNumber = 1
            //};
            var webQuery = new SearchBlogPostsQuery();
            //---------
            var query = new SearchCustomEntityRenderSummariesQuery();
            query.CustomEntityDefinitionCode =
BlogPostCustomEntityDefinition.DefinitionCode;
            query.PageNumber = webQuery.PageNumber;
            query.PageSize = 30;
            query.PageNumber = 1;
            // Publish status defaults to live, but we can use the current
visual editor
            // state to allow us to show draft blog posts when previewing a
draft page.
            var state = await _visualEditorStateService.GetCurrentAsync();
            query.PublishStatus =
state.GetAmbientEntityPublishStatusQuery();

            // TODO: Filtering by Category (webQuery.CategoryId)
            // Searching/filtering custom entities is not implemented yet
            var entities = await
_customEntityRepository.SearchCustomEntityRenderSummariesAsync(query);
            var viewModel = MapBlogPosts(entities);
            var pagedResult = await
_domainRepository.ExecuteQueryAsync(query);

            //// Examples of various properties and methods on
IPagedResult<TResult>
            ICollection<CustomEntityRenderSummary> pagedItems =
pagedResult.Items;
            int totalNumberOfItemsWithoutPaging = pagedResult.TotalItems;
            bool isFirstPage = pagedResult.IsFirstPage();
            bool isLastPage = pagedResult.IsLastPage();
            return View(viewModel);

        }

        [Obsolete]
        private PagedQueryResult<BlogPostSummary>
MapBlogPosts(PagedQueryResult<CustomEntityRenderSummary> customEntityResult)
        {
            int pageNumber;
            if (TempData["pageId"] == null)
            {
                pageNumber = 1;
            }
            else
            {
                pageNumber = Convert.ToInt32(TempData["pageId"]);
            }
            int pageSize = 5;
            var blogPosts = new
List<BlogPostSummary>(customEntityResult.Items.Count());
            foreach (var customEntity in customEntityResult.Items)
            {
                var model = (BlogPostDataModel)customEntity.Model;
                var blogPost = new BlogPostSummary();
                blogPost.Title = customEntity.Title;
                blogPost.ShortDescription = model.ShortDescription;
                DateTime tempDate = customEntity.CreateDate;
                blogPost.PostDate = tempDate.ToString("MMMM dd, yyyy");
                blogPost.FullPath = customEntity.PageUrls.FirstOrDefault();
                blogPost.CategoryId = model.CategoryIds.SingleOrDefault();
                blogPosts.Add(blogPost);
            }
            TempData["blogPostUrl"] =
JsonConvert.SerializeObject(blogPosts);
            return customEntityResult.ChangeType(blogPosts.Skip((pageNumber
- 1)*pageSize).Take(pageSize));

This is my client side code
  @{

        var prevDisabled = !Model.IsFirstPage() ? "disabled" : "";
        var nextDisabled = !Model.IsLastPage() ? "disabled" : "";
    }
    <a href="#" id="prev" data-Id="@(Model.PageNumber-1)" class="btn
btn-primary btn-sm @prevDisabled">Previous</a>
    <a href="#" id="next" data-Id="@(Model.PageNumber+1)" class="btn
btn-primary btn-sm @nextDisabled">Next</a>


</section>
<script type="text/javascript">
    $('#prev').click(function (event) {
        event.preventDefault();
        var id = $(this).attr('data-Id');
        $.ajax({
            url: "/Utility/Blog?pg=" + id,
            type: "POST",
            dataType: "html",
            traditional: true,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $(".blog-layout-content").html("");
                $(".blog-layout-content").html(data);
            },
        });
    });
    $('#next').click(function (event) {
        event.preventDefault();
        var id = $(this).attr('data-Id');
        alert(id);
        $.ajax({
            url: "/Utility/Blog?pg=" + id,
            type: "POST",
            dataType: "html",
            traditional: true,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $(".blog-layout-content").html("");
                $(".blog-layout-content").html(data);
            },
        });
    });
</script>

Only 2 page render not render 3 rd

**Comment by JornWildt** [comment]
That was a lot of code :-) You already have pagination inside it, so please explain what your issue is?

**Comment by sourabhCofoundry** [comment]
Sir Please send me UI code how it working

**Comment by JornWildt** [comment]
I guess this is your problem:


```
    <a href="#" id="prev" data-Id="@(Model.PageNumber-1)" class="btn
btn-primary btn-sm @prevDisabled">Previous</a>
    <a href="#" id="next" data-Id="@(Model.PageNumber+1)" class="btn
btn-primary btn-sm @nextDisabled">Next</a>


</section>
<script type="text/javascript">
    $('#prev').click(function (event) {
        event.preventDefault();
        var id = $(this).attr('data-Id');
```

You set data-Id on the server side:

    data-Id="@(Model.PageNumber-1)"

But you never update it after fetching the first page, meaning it will always stay the same for the whole lifte time of the page. So you always pass the same page number when doing the ajax call.

**Comment by sourabhCofoundry** [comment]
Ok

**Comment by sourabhCofoundry** [comment]
One more query for categories .I have face a issue how to get categories
from database I have debug my code and check this line
var entities = await
_customEntityRepository.SearchCustomEntityRenderSummariesAsync(query);---
here all record get then I have filter record .I want to get here records
based on categories id.Please let me know how to set here where condition
and filter record.

**Comment by HeyJoel** [comment]
This is covered in issue #425, see [this answer](https://github.com/cofoundry-cms/cofoundry/issues/425#issuecomment-817956707). It looks like you've already found it.

**Comment by sourabhCofoundry** [comment]
Any example for e.g you provide cofoundry.master project

**Comment by nikunj-89** [comment]
How Do I make pagination in cofoundry. example given in doc but not good to understand without the example of html implimentation.
