### ISSUE TITLE
Create Table.

### ISSUE THREAD

**Issue by sunykumar** [cofoundry-cms/cofoundry#451]
I have try to create a table in cofoundry and store data in table. But I have Face a Issue .Please look at this issue 
An unhandled exception occurred while processing the request.
SqlException: Invalid object name 'app.Person'.
Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

Stack Query Cookies Headers Routing
SqlException: Invalid object name 'app.Person'.

**Comment by JornWildt** [comment]
> `SqlException: Invalid object name 'app.Person'`

Well, you obviously haven't created the database table "Person". So start looking at how you try to do that and why that failed.

**Comment by sunykumar** [comment]
It's resolve issue .
