### ISSUE TITLE
customize admin panel.

### ISSUE THREAD

**Issue by sunykumar** [cofoundry-cms/cofoundry#452]
How to customize admin panel side (for e.g I have try to click a Save & Publish button then Hit my custom Method .Please let me know it's possible or not ) button in cofoundry.

**Comment by JornWildt** [comment]
Sorry, but is rather difficult to understand what you are asking. Take a look at https://www.cofoundry.org/docs/admin-panel/dashboard-customization to see how much you can customize the dashboard (it is not much).

**Comment by HeyJoel** [comment]
Customizing the admin panel is not currently supported. You can fork the project and change it as you wish, but no support is offered to do that.

If you need to run some .NET code when an entity or page is saved or published then you can use the [Message Aggregator](https://www.cofoundry.org/docs/framework/message-aggregator) to subscribe to the event.
