### ISSUE TITLE
Execute command in background

### ISSUE THREAD

**Issue by JornWildt** [cofoundry-cms/cofoundry#453]
I have a command that reads a custom entity, calls a slow external service and then sends an e-mail. This command is invoked through a standard ASP.NET WebAPI controller.

Now I want to execute that command in the background. I do like this:

```
[HttpPost]
public object Post()
{
  // Start as background task - don't wait for completing as it may take some time.
  _ = RunCommandInBackground(ServiceProvider);
  return Ok();
}

public async Task RunCommandInBackground(IServiceProvider serviceProvider)
{
  using (var scope = ServiceProvider.CreateScope())
  {
    var cmd = new SendStatusMailCommand();
    await ApiResponseHelper.RunCommandAsync(cmd);
  }
}
```

Very soon I realize that it is not going to work as the ApiResponseHelper gets disposed before it is invoked. Then I realize that all the database transaction handling is most likely also going haywire when the command is executed after the controller has completed the request.

So, question ... is there a standardized way to execute a command in the background as a side effect of executing an HTTP API controller method?

Thanks :-)

**Comment by HeyJoel** [comment]
I've actually written a module for this, but I've been too busy to tidy it up and open source it. It basically allows you to call `_domainRepository.QueueCommandAsync(command);` and it will be added to a queue and executed by a background process that runs periodically. It handles failurs/retries etc and shows the command queuein the admin panel.

That doesn't help you now particularly.... 

I'm wondering why you're using `APIReponseHelper`? If you're using fire and forget, then you're not going to be able to handle the result of your command execution, surely you're expecting the controller to return OK while the result is being executed?

Instead you should probably just resolve `IDomainRepository` in your scope and execute the command directly.

Having said that, if there's any errors in your task they aren't going to get caught or handled, so perhaps I might advise looking into [fire and forget with hangfire](https://duckduckgo.com/?q=fire+and+forget+with+hangfire), or if you want to do it in vanilla .NET do look into [best practices](https://duckduckgo.com/?q=fire+and+forget+.net+core).

**Comment by JornWildt** [comment]
> I'm wondering why you're using `APIReponseHelper`?

Yes, that is a mistake - a leftover from when the implementation was synchronous. But it showed me the issue of things that get disposed when the HTTP request is done - and then is unavailable to the background task.

I'll see what I can do with `IDomainRepository` directly.

**Comment by HeyJoel** [comment]
Everything in your task should be resolved from your new DI scope and not from the controller scope, it looks like you were referencing the api helper attached to the controller scope. 

Your new DI scope is resolved from the root context and will have it's own lifetime, so anything you resolve from there should behave as you expect.

**Comment by JornWildt** [comment]
Thank, IServiceProvider is new for me, so I wasn't sure what it did - just copy/pasted some stackoverflow answer to get started 😁

Now you are at the keyboard (sorry) - how do I log stuff? I'm trying this:

```
    public async Task RunCommandInBackground(IServiceProvider serviceProvider)
    {
      using (var scope = ServiceProvider.CreateScope())
      {
        ILogger<SendStatusMailApiController> logger = scope.ServiceProvider.GetRequiredService<ILogger<SendStatusMailApiController>>();
        try
        {
          var cmd = new SendStatusMailCommand();
          await scope.ServiceProvider.GetRequiredService<IDomainRepository>().ExecuteCommandAsync(cmd);
        }
        catch (Exception ex)
        {
          logger.LogError(ex, $"Failed to create or send status mail: {ex.Message}");
        }
      }
    }
```

But nothing shows up in the Cofoundry log page even though I step through the exception handler in the debugger.

**Comment by JornWildt** [comment]
Never mind, found it: https://github.com/cofoundry-cms/Cofoundry.Plugins.ErrorLogging/blob/master/src/Cofoundry.Plugins.ErrorLogging/Domain/Services/IErrorLoggingService.cs

That seems to be it. Thanks again for your help.

**Comment by HeyJoel** [comment]
Yeah thats it. The error logging module predates .NET Core and so it isn't integrated with the new logging framework.

At some point I'd like to get around to building a new one and it will just hook into something like Serilog, which is a better option anyway if you dont need the integrated admin screens.
