### ISSUE TITLE
Intercept the save process

### ISSUE THREAD

**Issue by kenan-kajkus** [cofoundry-cms/cofoundry#457]
My intention is to send the data to an API while saving. At the moment I send the data to the API when confirming the form field but it should save on pressing the save button. Is there any way of doing this? 

![image](https://user-images.githubusercontent.com/10548824/128304566-36f649c6-bea9-48bd-b568-4139d3010c7d.png)

**Comment by HeyJoel** [comment]
Have you looked into the [Message Aggregator](https://www.cofoundry.org/docs/framework/message-aggregator)? I guess you might be looking for `PageVersionBlockAddedMessage` and/or `PageVersionBlockUpdatedMessage`. 

There's no front-end events for you to hook into there.

**Comment by HeyJoel** [comment]
Closing, inactive.
