### ISSUE TITLE
Page Template has two Regions but Admin says it has none

### ISSUE THREAD

**Issue by irdublu** [cofoundry-cms/cofoundry#458]
I hit this problem with most of my trial projects.  The _Home.cshtml page, has two regions with the original wording.  The first time I run the program it works fine.

At some point the web page stops showing any regions.  They still exist in the unaltered code but when in Admin it states the Template has no regions and so the page cannot display any.

I assume I do something to cause this but have no idea what.

No matter what I do to the code or in Admin, I can never get the Home page to accept it has regions, so resort to wiping the database and starting again, hardly ideal.

Can anyone help me diagnose what it happening?

**Comment by HeyJoel** [comment]
Hi there, can you help me understand a little more about your setup, is it literally one of the sample projects, or your own templates? If so maybe you could provide the code for the template?

I suppose if you're saying the template is unaltered, then it could be something else you are doing, so perhaps let me know what sort of things are you doing e.g have you created any new templates? Are you creating or editing pages? Have you altered the homepage content?

**Comment by irdublu** [comment]
Thanks for quick response.
I was browsing some other Issues and saw how someone had commented code in their template that stopped it working.  I think your response was that comments would be allowed in version 0.9.0.  I had commented out the code that refers to the blogs.  As an experiment, I deleted the code and now the template is recognised and works.  I wish I had seen the other Issue and tried this before bothering you.
Thanks again.

**Comment by HeyJoel** [comment]
Ah, so it seems something to do with comments in templates is still not working. Could you paste the template code here so i can try and reproduce the issue?

**Comment by irdublu** [comment]
Hi Joel
Thanks again for getting involved in this.  I have tried with a number of CMSs e.g. Umbraco, Orchard, Pirahna and many more but found them using old technology or, not only complex for me to learn but far too hard for any non-computer literate editor.  So far CoFoundry seems ideal for both categories.  Thank you.
Here is the code.  I’m using version 0.9.1.  Let me know if I can help with anything else.

@model IPageViewModel
@inject ICofoundryTemplateHelper<IPageViewModel> Cofoundry

@Cofoundry.Template.UseDescription("This template should only be used for the homepage")

<div class="hero-banner">
          <img src="/images/hero-banner-bg.jpg">
          @*<img src="../App_Data/Files/Images/1.jpg">*@
          <div class="hero-banner__overlay"></div>
</div>

<div class="container">
    <div class="row content-block">
        <div class="col-sm-12">
            <h1>
                @(await Cofoundry
                    .Template
                    .Region("Introduction Title")
                    .AllowBlockType<PlainTextDataModel>()
                    .InvokeAsync())
            </h1>
            @(await Cofoundry
                .Template
                .Region("Introduction")
                .AllowBlockType<RichTextWithMediaDataModel>()
                .EmptyContentMinHeight(200)
                .InvokeAsync())
        </div>
    </div>

    @*<div class="row blog-cards">
        <div class="col-sm-12 ">
            <h2>From our blog</h2>
        </div>

        @await Component.InvokeAsync("HomepageBlogPosts")
    </div>*@
</div>

Regards
Ian

**Comment by HeyJoel** [comment]
Thanks for the feedback, much appreciated.

I've found the bug, I'll see if I can get time a bit later today to put a fix in. For now, best just avoid razor comments if you can (or multiple comments in a template file at least).

**Comment by HeyJoel** [comment]
Fix will be published in v0.9.2 soon.

**Comment by HeyJoel** [comment]
v0.9.2 is now published.
