### ISSUE TITLE
Inject user on startup.

### ISSUE THREAD

**Issue by kenan-kajkus** [cofoundry-cms/cofoundry#475]
Is there a way to inject a user with credentials on startup. We need this user because we bypass cofoundrys login by our authentication.

**Comment by HeyJoel** [comment]
I'm not sure exactly what you want to do, but here's a couple of pointers that might help you:

- Running code at startup can be done using the [Auto Update](https://www.cofoundry.org/docs/framework/auto-update) part of the framework
- You can register a user and login using the relevant APIs as demonstrated in the [SPA Sample](https://github.com/cofoundry-cms/Cofoundry.Samples.SPASite/blob/master/src/Cofoundry.Samples.SPASite.Domain/Domain/Members/Commands/RegisterMemberAndLogInCommandHandler.cs)

If that doesn't cover it, please can you describe in more detail what you want to achieve.

**Comment by HeyJoel** [comment]
Inactive, closed

**Comment by kenan-kajkus** [comment]
I am sorry for the late reply. We deploy predefined websites and need to add a custom user at start time. Our solution is to inject our "Admin" user via sql on startup, as you mentioned. Additionally we created a service to add useres via API.
