### ISSUE TITLE
Do you plan to update to dotnet core 6.

### ISSUE THREAD

**Issue by kenan-kajkus** [cofoundry-cms/cofoundry#486]
Hey, this is only a question in terms of future compatibility.

**Comment by HeyJoel** [comment]
Hey there. I have this planned for v0.11, after the rather large v0.10 is complete. I'm expecting v0.11 to be a fairly quick turn around as it will mostly be just the migration to .NET 6, but it depends on how much work is needed to make the upgrade.

**Comment by mtrutledge** [comment]
@HeyJoel How close are you to releasing v0.10?

**Comment by HeyJoel** [comment]
Possibly end of this week or start of next. The work is mostly done, I'm just writing up, testing and rolling out.
