### ISSUE TITLE
ErrorLogging Plugin: Limit overflow on long fields

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#508]
Long field values can cause the table to break in the list view of the error logging sample.

Copied issue:

3. Error log.  I've run the site today and the figures '1052' no longer appear on the Errors page and it is back to the 59 errors that it was before and no longer displays the number of errors.  There is something strange about the display.  Page 1 is fine but page 2 does not understand the viewport.  I attach two files to illustrate this.  Maybe you can tie this in with the image I sent when trying to filter errors in my opening post on this issue.
_______________________________________________________________________________________________________
![Error log 1](https://user-images.githubusercontent.com/19719089/161527465-0d428c24-8e85-42f8-b326-4ddfc8a45b66.JPG)
_______________________________________________________________________________________________________
![Error log 2](https://user-images.githubusercontent.com/19719089/161527544-dcf80431-57bd-4392-98b6-d24c410a50b9.JPG)
_______________________________________________________________________________________________________
Even though the top bar to illustrate how much more can be viewed shows a little bit more can be seen, even when the screen is maximised, only a small part of the url is visible and User Agent and Date are always hidden.  Is this just my installation or have I found something new?  Do you want these matters raised in a separate Issue to keep this one just on data deletion issues?

_Originally posted by @irdublu in https://github.com/cofoundry-cms/cofoundry/issues/507#issuecomment-1087400790_

**Comment by irdublu** [comment]
I'm adding to this as I have found the elusive number of errors.  Even though my db lists 77 discrete errors, when I click on one and the details such as the Message and Stack trace appear, so does the number of errors.  Image attached.

The number decrements as I open each error down the list

![Error Log Error Number](https://user-images.githubusercontent.com/19719089/161942434-c62bad90-b9cb-4ca8-836c-aeb95bfb8699.JPG)
.

**Comment by HeyJoel** [comment]
That number is the Error Id, which is auto-incremementing but can skip ahead by 1000 when SQLServer restarts (same for any auto-incrementing id), so it doesn't necessarily mean you have 1044 errors. 

I can clarify this in the interface though with something like "Errors > Id:1044", since there isn't really a more logical title identifier for an individual error.

**Comment by irdublu** [comment]
Yes, thanks.  Checking the table, I see this now.  The greater than symbol > misled me.

**Comment by HeyJoel** [comment]
Fixed, will be released alongside Cofoundry v0.11
