### ISSUE TITLE
Open Graph Image.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#509]
Hello, I have faced an issue I have uploaded an open graph Image it's uploaded successfully. But I have shared a blog post on Facebook and LinkedIn it's not accessed open graph Image it's showing Profile Image. I have checked the open graph Image in the source code.

**Comment by HeyJoel** [comment]
Cofoundry allows you to add an open graph image to a page, but it's up to you to render the image in your HTML code to meet the specification of your social media platform.

**Comment by sourabhCofoundry** [comment]
okay thanks
