### ISSUE TITLE
Samples.Mail.Templates: view file error when resetting password

### ISSUE THREAD

**Issue by irdublu** [cofoundry-cms/cofoundry#511]
I'm not sure if this is connected with the changes in #479 but when using **Samples.Mail src** as a guide and when I am **resetting a password**, I get the error:-

`Couldn't find a text or html mail template file for '~/Cofoundry/Admin/MailTemplates/Templates/AccountRecoveryMailTemplate'`

The file AdminMailTemplateBuilder.cs
public async Task<IMailTemplate>BuildPasswordResetTemplateAsync(IPasswordResetTemplateBuilderContext context)
states the ViewFile is
`"~/Cofoundry/Admin/MailTemplates/Templates/AccountRecoveryMailTemplate";`
but should surely be 
`"~/Cofoundry/Admin/MailTemplates/Templates/PasswordResetMailTemplate";`
once I change this, it works as expected.

**Comment by HeyJoel** [comment]
Yep, that's a bug, I've just pushed a fix. Thanks.
