### ISSUE TITLE
Implement Postmark

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#512]
Hello, everyone I have faced one issue in cofoundry . I have implemented PostMark in cofoundry for sending Emails but face an issue . Emails sent successfully but Data not sent.

For e.g code
```csharp
var message = new TemplatedPostmarkMessage
                {
                    From = postFromEmailAddress,
                    To = sendNotification.toEmail,
                    TemplateAlias = "welcome",
                    TemplateModel = new Dictionary<string, object> { { "Sender_Name", "Sunny" } }
                };
                var client = new PostmarkClient(postMarkKey);
                await client.SendMessageAsync(message);
```

I have sent the user name under the "Sender_Name" properties it's not been sent.

**Comment by HeyJoel** [comment]
This doesn't look like a Cofoundry issue, I can't see any Cofoundry specific code here.

FYI you can format code [using markdown (backticks)](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) or by highlighting your code in the comment box and clicking on the `<>` button at the top of the editor.

**Comment by sourabhCofoundry** [comment]
Yes, this is not cofoundry code but I have implement this code in cofoundry project .

**Comment by sourabhCofoundry** [comment]
HeyJoel - May be cofoundry does not support postmarks because I have to try create new project and Implement this not working.

**Comment by sourabhCofoundry** [comment]
Any update on it and one suggestion for you please check once postmark your side. Because it's a major issue.
