### ISSUE TITLE
REDIRECT TO SIGN-IN flag not saving

### ISSUE THREAD

**Issue by gofrancis** [cofoundry-cms/cofoundry#513]
The REDIRECT TO SIGN-IN flag under ACCESS CONTROL > Violation Action does not seem to be saving.

![Cofoundry-Redirect-to-SignIn](https://user-images.githubusercontent.com/10526409/164936932-8fabe9e5-ab8c-4d39-95f1-7e31733abdea.png)

**Comment by HeyJoel** [comment]
You'll need to add an access rule before that option can be saved, as the redirect target is dependent on the user area selected in the access rule. In any case, perhaps those options should be disabled until an access rule has been created.

**Comment by gofrancis** [comment]
Thanks for your reply Joel.

I did add an access rule. But still it won't save the settings. 

![Screenshot_20220427_170259_com android chrome](https://user-images.githubusercontent.com/10526409/165525344-d1ab34cb-d7d1-4616-96ae-21cb380b6bdc.jpg)

For now, I added the values in the table manually to enable the redirect.

**Comment by HeyJoel** [comment]
Ok, yep I can see now that that's a bug in the admin panel front-end. When there is a single user area it's supposed to automatically select it by default, but it is not being set correctly.

**Comment by HeyJoel** [comment]
Fixed, will be released in 0.10.3
