### ISSUE TITLE
Remove google fonts to be GDPR compliant

### ISSUE THREAD

**Issue by rwolfdev** [cofoundry-cms/cofoundry#517]
I would like to remove the Google Fonts from the admin interface to be GDPR compliant (in Germany, there is a decision by the Federal Court of Justice that Google Fonts may only be integrated locally.).

Where can I find them or is it generally possible to include them directly in the future?

Thanks for the help!

**Comment by HeyJoel** [comment]
We actually removed the use of the font a long time ago in favor of a native font-stack, but must have forgotten to remove the reference in the layout. I've now removed the reference.

This will be in release 0.11.2 which should be published shortly.
