### ISSUE TITLE
Used package (Underscore@1.8.3) in Web Admin contains known vulnerabilities [Medium]

### ISSUE THREAD

**Issue by rwolfdev** [cofoundry-cms/cofoundry#518]
The web admin package uses a third-party library (underscore@1.8.3) that has a known vulnerability.
Reference: https://security.snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984 

Updating this library to a newer version would increase security. The latest version of this package has no known security vulnerabilities at the moment (https://security.snyk.io/package/npm/underscore).

**Comment by HeyJoel** [comment]
The admin panel doesn't use the vulnerable templating feature, and so won't be affected, but I'll see about getting it updated so it doesn't come up in automated security checks.

**Comment by HeyJoel** [comment]
Fixed in 0.11.3
