### ISSUE TITLE
Add new property in User Table

### ISSUE THREAD

**Issue by ciitumar047** [cofoundry-cms/cofoundry#522]
Hi, team I want to know we can add new property in user table in cofoundry identity .?

**Comment by HeyJoel** [comment]
Hi there, this isn't possible in the framework at the moment, but is covered by #176, so I will have to close this.

If you don't need an admin UI, a work around is just to maintain any additional data yourself in a separate table and use the [messaging](https://www.cofoundry.org/docs/framework/message-aggregator) framework to handle user add/deletion events.
