### ISSUE TITLE
Faced this error.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#533]
Hello team Please help me I have faced this error.
![Screenshot_3](https://user-images.githubusercontent.com/80239301/228140479-6e8fb57c-3e69-41ef-8503-e62689df60af.png)

**Comment by HeyJoel** [comment]
It looks like you are trying to upgrade to a newer version of Cofoundry. Which version are you upgrading from, and which version are you upgrading to?

Things to check:

- Make sure all your projects reference the same version of Cofoundry.
- If you are pointing multiple Cofoundry instances running different versions of Cofoundry at the same database (e.g. dev, staging, production), don't do that.
- If you're upgrading through several versions of Cofoundry, you could try restoring your db to before the update and then upgrade though each 0.X (minor) release in turn, running the application (which applies the db updates) after each upgrade.
- If you've made any alterations to Cofoundry db tables or objects, then that could cause an issue during upgrades, but I can't help you with that.

Lastly, you can check the `Cofoundry.ModuleUpdateError` table for details of any errors that occurred during the auto update process.

**Comment by sourabhCofoundry** [comment]
Ok . HeyJoel I check this

**Comment by sourabhCofoundry** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/80239301/228214622-10e09e0d-d3c3-4c26-8244-2478bf1fb56a.png)
Now this error faced.

**Comment by HeyJoel** [comment]
Can you answer the questions in my original response and give me some sort of narrative on what you have tried and how you arrived at the next error you posted? I can't help you if you don't provide any information.

Please dont @ me, or bug me for updates, helping you comes out of my spare time and my spare time is important to me.
