### ISSUE TITLE
Late server response.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/cofoundry#534]
@HeyJoel Sorry I am asking the same question again. Actually what is happening to my blog page? I have a total of 102 blogs which are taking a lot of time to load the page! And my other pages which have static data, those pages get loaded quickly. Can't understand whether there is some issue of cofoundry or something else.

**Comment by sourabhCofoundry** [comment]
@HeyJoel This is the URL of my website. clicking on the blog page whose response comes after a long time. And clicking on any page, the response comes quickly.

**Comment by HeyJoel** [comment]
Dupicate of #527 and #531. [I already replied](https://github.com/cofoundry-cms/cofoundry/issues/531#issuecomment-1480007929) and you didn't respond.
