### ISSUE TITLE
Cant update User

### ISSUE THREAD

**Issue by amitavayourflow** [cofoundry-cms/cofoundry#536]
// When applying the update we can use the patch overload
// on UpdateAsync so we only have to update the properties we
// have data for
await _advancedContentRepository
    .WithElevatedPermissions()
    .WithModelState(this)
    .Users()
    .Current()
    .UpdateAsync(c =>
    {
        c.DisplayName = "Mine";
        c.Email = profile.Email;
    });
    
Cant update the user facing this error.
  Action<TCommand> commandPatcher) in IDomainRepositoryExtensions.cs
  commandPatcher(command);
  Can anyone assist

**Comment by HeyJoel** [comment]
Please add the full exception details.

**Comment by amitavayourflow** [comment]
NullReferenceException: Object reference not set to an instance of an object.
TheMummyShake.CofoundaryCMS.Controllers.AccountController+<>c__DisplayClass20_0.<UpdateProfile>b__0(UpdateCurrentUserCommand c) in AccountController.cs
+
                  c.FirstName = profile.FirstName;
Cofoundry.Domain.IDomainRepositoryExtensions.PatchCommandAsync<TCommand>(IDomainRepository repository, Action<TCommand> commandPatcher) in IDomainRepositoryExtensions.cs
+
        commandPatcher(command);
TheMummyShake.CofoundaryCMS.Controllers.AccountController.UpdateProfile(ProfileDTO profile) in AccountController.cs
+
            await _advancedContentRepository
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in AutoUpdateMiddleware.cs
+
                await _next.Invoke(cx);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by amitavayourflow** [comment]
Cofoundry.Domain.Internal.PermissionValidationService.EnforcePermission(IPermissionApplication permission, IUserContext userContext) in PermissionValidationService.cs
+
            throw new PermissionValidationFailedException(permission, userContext);
Cofoundry.Domain.Internal.PermissionValidationService.EnforcePermission(IEnumerable<IPermissionApplication> permissions, IUserContext userContext) in PermissionValidationService.cs
+
            EnforcePermission(permission, userContext);
Cofoundry.Domain.Internal.ExecutePermissionValidationService.Validate<TCommand>(TCommand command, ICommandHandler<TCommand> commandHandler, IExecutionContext executionContext) in ExecutePermissionValidationService.cs
+
            _permissionValidationService.EnforcePermission(permissions, executionContext.UserContext);
Cofoundry.Domain.CQS.Internal.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
Cofoundry.Domain.CQS.Internal.CommandExecutor.ExecuteCommandAsync<TCommand>(TCommand command, IExecutionContext executionContext) in CommandExecutor.cs
+
            throw;
Cofoundry.Domain.CQS.Internal.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in CommandExecutor.cs
+
            await (Task)genericExecuteMethod.Invoke(this, new object[] { command, executionContext });
Cofoundry.Domain.Extendable.DomainRepositoryExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in DomainRepositoryExecutor.cs
+
        await _commandExecutor.ExecuteAsync(command, executionContext);
Cofoundry.Domain.IDomainRepositoryExtensions.PatchCommandAsync<TCommand>(IDomainRepository repository, Action<TCommand> commandPatcher) in IDomainRepositoryExtensions.cs
+
        await repository.ExecuteCommandAsync(command);
TheMummyShake.CofoundaryCMS.Controllers.AccountController+<UpdateProfile>d__20.MoveNext()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in AutoUpdateMiddleware.cs
+
                await _next.Invoke(cx);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger<ErrorLoggingMiddleware> logger, IErrorLoggingService errorLoggingService)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

If Not used elevated permission

**Comment by HeyJoel** [comment]
Extracted better error handling task to #537. Closing.
