### ISSUE TITLE
Not able to see pagination on asset picker pop up

### ISSUE THREAD

**Issue by akash0234** [cofoundry-cms/cofoundry#542]
![image](https://github.com/cofoundry-cms/cofoundry/assets/79512555/eb07561f-7437-43e8-b16a-62d6f89ed28a)

Image and Document assets are showing only 1 page records.

**Comment by akash0234** [comment]
![image](https://github.com/cofoundry-cms/cofoundry/assets/79512555/36ab08be-f67a-4e52-bf0e-51443b5fdec9)

I'm sure there is more than 30 assets.. I'm in middle of a project could you please suggest what actions can resolve this issue

**Comment by HeyJoel** [comment]
I'm just looking back at your screenshot, that doesn't look like the current built-in document asset picker - you shouldn't be able to add images as document assets, they should be added as "Image Assets". Can you provide more information on what you're doing?

- What version of Cofoundry are you running?
- Have you made any modifications to Cofoundry or overriden any Cofoundry services?
- What version of .NET?
- What are you adding documents to? e.g. a custom entity model via `[DocumentCollection]`?

**Comment by akash0234** [comment]
1. Cofoundry 0.11.3
2. Yes Right Now im using DocumentAsset Services to serve my images (As There was no direct support to svgs and webps)
3. I'm Using Dotnet6.0
4.  Im Using the below Syntax in Custom Entity Model or Page Block Model Both has same result
[Document(FileExtensions = new string[] { "svg", "webp", "jpg", "jpeg", "png" })]

**Comment by HeyJoel** [comment]
If you have overriden the document asset picker dialog then you'll need to apply the [changes in my commit yesterday](https://github.com/cofoundry-cms/cofoundry/commit/daedf566347d6146e3905f6d8d355736a03c44b6#diff-4b7f742b47c1e88b99fbdf5da1e2d4871735e4f5d372a9b66fb01422ee11265f), specifically fixing the reference to the pager control in `DocumentAssetPickerDialog.html` from:

```html
 <cms-pager result="result" query="query"></cms-pager>
``` 

to 
      
```html
<cms-pager cms-result="result" cms-query="query"></cms-pager>
```

**Comment by akash0234** [comment]
I Merged Your Patch it fixed My Paging Issue. although i lost my preview code, I'll Manage to bring back the same, Thanks For the constant support.
