### ISSUE TITLE
When Updating account with same password, it doesn't restrict me

### ISSUE THREAD

**Issue by akash0234** [cofoundry-cms/cofoundry#544]
[HttpPost]
 public async Task<IActionResult> ForgotPasswordSubmit(string token, string newpassword)
 {
     try
     {
         //Check If Old Password
       

           await _advancedContentRepository
                         .Users()
                         .AccountRecovery()
                          .CompleteAsync(new CompleteUserAccountRecoveryViaEmailCommand()
                          {
                              NewPassword = newpassword,
                              UserAreaCode = MemberUserArea.Code,
                              Token = token
                          });

         TempData["ResetSuccess"] = "Password Reset Successful";
         return RedirectToAction("UserLoginRegister");
     }
     catch (Exception ex)
     {
         TempData["ResetSuccess"] = "Account Recovery Already Completed";
         return RedirectToAction("UserLoginRegister");
     }
    

 }
  https://www.cofoundry.org/docs/user-areas/data-apis/account-recovery
 As per documentation, it should show error ,
 also I want to understand the last point which says "The token will be automatically re-validated, throwing a validation exception if it is invalid."

How to handle the revalidated status.

**Comment by HeyJoel** [comment]
If the token has already been used or is invalid then executing `CompleteUserAccountRecoveryViaEmailCommand` will throw a `ValidationErrorException` with the relevant error code and message. The [user areas sample repository](https://github.com/cofoundry-cms/Cofoundry.Samples.UserAreas) includes an [example of this in the AuthenticationSample project](https://github.com/cofoundry-cms/Cofoundry.Samples.UserAreas/blob/main/src/AuthenticationSample/Pages/Members/ResetPassword.cshtml.cs). That project uses Razor Pages but the other project in that solution uses MVC if you want to see examples of calling similar auth APIs from MVC.

Your code looks like it would show an error, however you are catching a non-specific `Exception`, whereas you may be better off handling only `ValidationErrorException`, or using the built-in `WithModelState` extension to bind validation errors to model state as documented in the [content repository docs](https://www.cofoundry.org/docs/content-management/accessing-data-programmatically#influencing-execution-with-modelstate). Doing this will populate `ModelState` with the correct message associated with the error, which you can show in your UI using the standard ASP.NET mechanisms.

**Comment by akash0234** [comment]
Thanks for the info.. 
I understood the workings of auth token. 
It led me to find other way to solve it.. 
I'm sending the encoded email id as parameter in email . 
While

**Comment by akash0234** [comment]
Although I Would Suggest to Add Module to validate old password. In Upcoming update..
Thanks for always helping and swift replies. Appreciate your work
