### ISSUE TITLE
Page/Entities version numbers to be stored in database

### ISSUE THREAD

**Issue by stephenthornton** [cofoundry-cms/cofoundry#67]

**Comment by HeyJoel** [comment]
This is a pre-requisite to adding paging to the page/entities version listing. We should at least alter the version queries to make this pageable while this is being done. If it's not too much effort to add paging to the view too then implement that too.

**Comment by HeyJoel** [comment]
Version numbers have been added and paging for versions has been implemented in the admin UI.

Fixed and will be released in v0.4
