### ISSUE TITLE
Ability to hide custom entities from the navigation

### ISSUE THREAD

**Issue by stephenthornton** [cofoundry-cms/cofoundry#69]
No we have the ability to create custom entities in context to another custom entity (within pickers), it could make the interface cleaner by allowing some "secondary" custom entities to be hidden from the main nav.

Maybe we could provide a way to hide/show secondary CE's or have dividers etc

**Comment by unsafecode** [comment]
Would it also be possible not to show some of  the predefined entities, like pages?

**Comment by HeyJoel** [comment]
Currently you can hide features in the admin menu using [roles and permissions](https://github.com/cofoundry-cms/cofoundry/wiki/Roles-&-Permissions) to restrict access to the features you want to hide. However, you are not able to hide features from the super administrator role. Typically we create an 'Administrator' role that we use to remove uneccessary features for our clients.

We could do better here though, so I've split this out into two new issues that deal with slightly separate features and will close this one:

- #159 Disable built-in features / remove items from admin panel navigation
- #160 Customizable admin navigation
