### ISSUE TITLE
.net core pull content through API?

### ISSUE THREAD

**Issue by dotnetshadow** [cofoundry-cms/cofoundry#85]
Hi there, 

The project looks great. I understand that you are looking to migrate to .net core, but in the interim would there be any way to at least access the content in a .net core application.

The backend where you define your pages could still remain in .net old for the short time, but have a way to be able to access and the pull out content from the database in .net projects?

**Comment by HeyJoel** [comment]
.net core is still some way off for us and we're first looking at an MVC5 to asp.net core migration so we can get the api surface area locked in. This work will be kicking off when im back from holiday week after next.

One of the main issues we're expecting  with a .net core migration is the maturity of EF core and we'll be exploring other orm options to make the transition possible. So porting the raw data access won't happen too quickly but we'll have a better idea of what that's going to take in the next month or so.

Your only option on .net core for time being is  either raw db access or using our data apis to make your own web api that exposes the data your app needs in a full fat .net site.

Unfortunately we dont have timescales yet but i can say that almost all our front-end devs use macs so we're really keen on enabling cross platform development soon.


From: dotnetshadow
Sent: Saturday, 11 March, 09:04
Subject: [cofoundry-cms/cofoundry] .net core pull content through API? (#85)
To: cofoundry-cms/cofoundry
Cc: Subscribed

Hi there,

The project looks great. I understand that you are looking to migrate to .net core, but in the interim would there be any way to at least access the content in a .net core application.

The backend where you define your pages could still remain in .net old for the short time, but have a way to be able to access and the pull out content from the database in .net projects?

**Comment by HeyJoel** [comment]
.NET Core now supported in the [0.2 release](https://www.cofoundry.org/blog/11/migrating-our-cms-to-net-core-cofoundry-02-released), so I'm closing this.
