### ISSUE TITLE
Pasting into an html editor from a Google doc fails to save the content

### ISSUE THREAD

**Issue by ricalebro** [cofoundry-cms/cofoundry#93]
The custom entity saves successfully without visible error but the content of the html field ignores the new value and retains the old value.
It works if you use the _remove formatting_ button first, and also seems to work pasting in formatted content directed copied off a normal web page.

**Comment by HeyJoel** [comment]
In our tests we could not replicate the behaviour. Could it be specific google docs formatting causing the issue?

**Comment by ricalebro** [comment]
I don't seem to be getting it now either so maybe it was something specific to that doc

**Comment by HeyJoel** [comment]
Closing for now. Let us know if it happens again.
